### DISCUSSION TITLE
Much lower compression on new pool with largely same settings

### DISCUSSION THREAD

**Discussion by mpeter50** [openzfs/zfs#16360] [Q&A] [answered]
I have a pool that I was using for a longer period to store various kinds of data, but I started moving some of them to a new pool, made of disks I was using in the first pool before I upgraded its disks.

Both pools use ashift=12, (on all datasets) lz4 compression, recordsize=1M.
I was copying a lot of data with rsync, with the intetion of eventually deleting them from the origin pool, but I have noticed that nearly all of my files are larger than they are on the origin pool. After looking into it, I see that for these files the contents are the same, and so the logical sizes too, however the physical sizes are larger on the new pool.

If I take a file that is well compressed on the origin pool, and make a copy on the same pool, I see that the copy is also well compessed by looking at the difference of the logical size and the size on disk.
If I copy that same file to the new pool, it is only very slightly compressed.

I should note that I created the pool with checksum=blake3 and recordsize=4M (limit increased), but when I noticed this difference, I have set these back to the values I was using on the origin pool, deleted all copied files, and started over. But that did not result in any difference.
I'm copying the data to a non-root dataset, but that inherits props from the root, and I have always set the mentioned props there.

I have compared the dataset and pool properties. The configurable native properties are basically the same, the only notable difference is the size of the pool, the vdev structure (the origin pool is a single raidz1 vdev, this new pool does not have any parity, its sole vdev is a Device Mapper virtual block device), the name and description, and the allowed features. Namely, in the old pool I dont have the following features enabled, but I have in the new one: `zilsaxattr`, `head_errlog`, `blake3`, `block_cloning`, and `vdev_zaps_v2`.

What is the cause of this difference? I would prefer to keep the compression capability of my old pool, because it has a meaningful impact on how soon would I need to upgrade.

This is what I'm using:
Proxmox 8 based on Debian 12
Linux kernel 6.8.8-2-pve
apophis@node804:/mnt/yellow_pool/Media $ zfs --version
zfs-2.2.4-pve1
zfs-kmod-2.2.4-pve1

**Comment by mpeter50** [comment]
I have attached exports of pool properties, and of one of the affected dataset's: [props.zip](https://github.com/user-attachments/files/16257738/props.zip)

Please ignore the size and free stat props, I'm in the process of copying all files again to have a bigger picture on the current effectiveness of compression.

**Comment by amotin** [comment]
> Both pools use ashift=12,

Are you sure that old pool really had ashift=12?  You should not look on the respective pool property, since it affects only newly added vdevs and its change later does not matter.  Look into on zdb output, which should show real ashift for each individual leaf vdev.

> (on all datasets) lz4 compression, recordsize=1M.

What is the average file size?  If files are very small, then recordsize may not matter if it is rarely/never reached.

> the origin pool is a single raidz1 vdev, this new pool does not have any parity, its sole vdev is a Device Mapper virtual block device

Pool topology may also matter.  For example, RAIDZ1 rounds up each allocation to a multiple of 2 allocation sizes, which may be only 1KB if ashift=9, but much more significant 8KB if ashift=12, while single vdev or mirrors round up only to 1 allocation size.  Mentioned Device Mapper does not tell me anything, since depending on its characteristics ZFS may increase ashift up to 16KB, if needed (again, look into zdb output).  If you use Device Mapper to create some sort of RAID under ZFS -- please don't, since you loose ZFS' ability to recover data from multiple copies.

**Reply by mpeter50** [reply]
sorry, forgot to place the reply as a reply to your comment. my reply is a new top level comment.

**Comment by mpeter50** [comment]
> Are you sure that old pool really had ashift=12? You should not look on the respective pool property, since it affects only newly added vdevs and its change later does not matter. Look into on zdb output, which should show real ashift for each individual leaf vdev.

Thats a good point, thanks!
In my case, the output of `zdb mypool` (mypool is the name of my origin pool) looks like this:
```
Cached configuration:
        version: 5000
        name: 'mypool'
        state: 0
        txg: 16797449
        pool_guid: 9066662378798912206
        errata: 0
        comment: 'First ZFS pool for general NAS'
        hostname: 'myhostname'
        com.delphix:has_per_vdev_zaps
        vdev_children: 1
        vdev_tree:
            type: 'root'
            id: 0
            guid: 9066662378798912206
            create_txg: 4
            children[0]:
                type: 'raidz'
                id: 0
                guid: 14516829785936615426
                nparity: 1
                metaslab_array: 65
                metaslab_shift: 34
                ashift: 12
                asize: 32006194855936
                is_log: 0
[...]
```

The vdev with guid of `14516829785936615426` is my only vdev.
Additionaly, from `zpool history` this is how I made the pool originally (thoguh with smaller storage capacity):
```
zpool create -f -o ashift=12 -O compression=lz4 -O recordsize=1M -m /mnt/zdata mypool raidz1 [...]
```

> What is the average file size? If files are very small, then recordsize may not matter if it is rarely/never reached.

On the dataset for which I have included the proprties export, most files range from 500 MB to 10+ (below 20) GB.
Total logical size is 406 GB for 213 files, which on the origin pool is compressed to 393 GB. On the new pool, this is compressed to 405 GB (435 777 767 424 bytes).
Sorry for not including size examples before. When sending I did not yet figure out that it is as simple as giving aggregate size examples. Sometimes the easisest things are the hardest..

> Mentioned Device Mapper does not tell me anything, since depending on its characteristics ZFS may increase ashift up to 16KB

`ashift=12` was explicitely defined at pool creation. That being said, here is my zpool history for the new pool:
```
2024-07-16.15:27:39 zpool create -o ashift=12 -O compression=lz4 -O checksum=blake3 -O recordsize=4M -m /mnt/yellow_pool yellow_pool /dev/mapper/yellow_pool_zfs_1
2024-07-16.19:46:03 zfs set atime=off yellow_pool
2024-07-16.19:52:20 zfs set exec=off primarycache=metadata yellow_pool
[created 4 datasets]
2024-07-17.01:11:00 zfs set recordsize=1M yellow_pool
2024-07-17.01:15:49 zfs inherit checksum yellow_pool
```

If it has significance, the Device Mapper virtual block device is a LUKS device of a full disk, no partition table.

> If you use Device Mapper to create some sort of RAID under ZFS -- please don't, since you loose ZFS' ability to recover data from multiple copies.

I dont, this is only a single layer of full disk encryption. This pool is intentionally without parity, it will only store replaceable data, backups, and other such things.

**Reply by amotin** [reply]
> `ashift=12` was explicitely defined at pool creation.

Good, but it is still only a request, which ZFS may ignore if underlying device needs bigger value, so make sure to check with zdb.

**Reply by mpeter50** [reply]
Oh, thats good to know. Here is the relevant ZDB output:
```
$ sudo zdb yellow_pool
```
```
Cached configuration:
        version: 5000
        name: 'yellow_pool'
        state: 0
        txg: 4
        pool_guid: 4486881383270724382
        errata: 0
        comment: 'mycomment'  
        hostname: 'myhostname'
        com.delphix:has_per_vdev_zaps
        vdev_children: 1
        vdev_tree:
            type: 'root'
            id: 0
            guid: 4486881383270724382
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 18031409987003214390
                path: '/dev/mapper/yellow_pool_zfs_1'
                whole_disk: 0
                metaslab_array: 256
                metaslab_shift: 34
                ashift: 12
                asize: 4000765444096
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_leaf: 130       
                com.delphix:vdev_zap_top: 131        
        features_for_read:
            com.delphix:hole_birth
            com.delphix:embedded_data
            com.klarasystems:vdev_zaps_v2

[...]
```

vdev with guid `4486881383270724382` is the only vdev.  `ashift` is 12.

Also, I have just noticed, is it ok to read the value from the "cached configuration" section when the pool is online?
ashift is also 12 in the MOS config, both for this and the origin pool.
