### DISCUSSION TITLE
cannot import dm-crypt pool after upgrade to 2.2.8

### DISCUSSION THREAD

**Discussion by aerusso** [openzfs/zfs#17474] [Q&A] [answered]
`zpool import` shows `no pools available to import`

but `zdb -l /dev/mapper/hydrapool` shows:

```
------------------------------------
LABEL 0
------------------------------------
    version: 5000
    name: 'hydrapool'
    state: 2
    txg: 13363676
    pool_guid: 11467606987605943141
    errata: 0
    hostname: 'hydra'
    top_guid: 1538874035715982282
    guid: 1538874035715982282
    vdev_children: 1
    vdev_tree:
        type: 'disk'
        id: 0
        guid: 1538874035715982282
        path: '/dev/disk/by-id/dm-name-hydrapool'
        devid: 'dm-uuid-CRYPT-LUKS1-01e0f8439ddf40b7917362c3a4140215-hydrapool'
        phys_path: '/dev/disk/by-uuid/11467606987605943141'
        whole_disk: 0
        metaslab_array: 256
        metaslab_shift: 32
        ashift: 13
        asize: 776321105920
        is_log: 0
        DTL: 515
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 0 1 2 3
```

`zpool import -d /dev/mapper/hydrapool` gives `no pools available to import` and `cat /proc/spl/kstat/zfs/dbgmsg` gives

```
1750381121   spa.c:6771:spa_tryimport(): spa_tryimport: importing hydrapool
1750381121   spa_misc.c:418:spa_load_note(): spa_load($import, config trusted): LOADING
1750381121   vdev.c:166:vdev_dbgmsg(): disk vdev '/dev/disk/by-id/dm-name-hydrapool': best uberblock found for spa $import. txg 13363676
1750381121   spa_misc.c:418:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=13363676
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading checkpoint txg
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading indirect vdev metadata
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Checking feature flags
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading special MOS directories
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading properties
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading AUX vdevs
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading vdev metadata
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading dedup tables
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading BRT
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Verifying Log Devices
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Verifying pool data
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Calculating deflated space
1750381121   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Starting import
1750381121   spa.c:8925:spa_async_request(): spa=$import async request task=2048
1750381121   spa_misc.c:418:spa_load_note(): spa_load($import, config trusted): LOADED
1750381121   spa_misc.c:418:spa_load_note(): spa_load($import, config trusted): UNLOADING
1750381175   spa.c:6771:spa_tryimport(): spa_tryimport: importing hydrapool
1750381175   spa_misc.c:418:spa_load_note(): spa_load($import, config trusted): LOADING
1750381175   vdev.c:166:vdev_dbgmsg(): disk vdev '/dev/mapper/hydrapool': best uberblock found for spa $import. txg 13363676
1750381175   spa_misc.c:418:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=13363676
1750381175   vdev.c:2506:vdev_update_path(): vdev_copy_path: vdev 1538874035715982282: vdev_path changed from '/dev/disk/by-id/dm-name-hydrapool' to '/dev/mapper/hydrapool'
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading checkpoint txg
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading indirect vdev metadata
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Checking feature flags
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading special MOS directories
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading properties
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading AUX vdevs
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading vdev metadata
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading dedup tables
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Loading BRT
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Verifying Log Devices
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Verifying pool data
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Calculating deflated space
1750381175   spa_misc.c:2311:spa_import_progress_set_notes_impl(): 'hydrapool' Starting import
1750381175   spa.c:8925:spa_async_request(): spa=$import async request task=2048
1750381175   spa_misc.c:418:spa_load_note(): spa_load($import, config trusted): LOADED
1750381175   spa_misc.c:418:spa_load_note(): spa_load($import, config trusted): UNLOADING
```

I run into this problem on both 2.2.8 and 2.2.7 kernels (actually this includes the zfs-2.2.8 staging branch, but not the rest of 2.2.8) using the 2.2.8 userspace.
