### DISCUSSION TITLE
Cannot remove log device from encrypted pool

### DISCUSSION THREAD

**Discussion by DanielSmedegaardBuus** [openzfs/zfs#8748] [Q&A] [answered]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu Server amd64
Distribution Version	| 19.04
Linux Kernel	| 5.0.0-13-generic
Architecture	| x64
ZFS Version	| 0.8.0-rc4
SPL Version	| 0.8.0-rc4

### Describe the problem you're observing
I initially created my pool on macOS using O3X 1.8.2. The system was an older Mac mini with a 500 GB SSD, on which I reserved two partitions for a log and a cache device.

The mini started to have issues running the pool, possibly due to being rather underpowered (4G mem, 1.4GHz i5), so I decided to move it to a more beefy MacBook Pro. I exported on the mini, and imported it on the Pro, where of course the log and cache partitions were not available.

I've now moved the pool to Ubuntu Server as macOS just has so many issues running it stably and performant (which may not be due to ZFS itself, but possibly the USB subsystem, as this is a USB-connected pool.

When I tried to remove the orphaned log device, I got:

```
daniel@titanic ~ sudo zpool remove titanic 3470644392946588961
cannot remove 3470644392946588961: Mount encrypted datasets to replay logs.
```

Thing is, the encrypted datasets were mounted and happy (actually just the one, "titanic" itself (I haven't yet created any other filesystems)).

Later, I was at the point where I was ready to add back a new log and cache device on the SSD on the Ubuntu Server rig. So I thought, given that I couldn't remove the missing log device, I'd try replacing it first.

So, I created a partition on my Air's SSD, and did:

```
daniel@titanic ~ sudo zpool replace -f titanic 3470644392946588961 /dev/disk/by-partlabel/slog
cannot replace 3470644392946588961 with /dev/disk/by-partlabel/slog: new device has a different optimal sector size; use the option '-o ashift=N' to override the optimal size
```

This was a bit weird I thought (adding a log device to an ashift=12 pool seriously adds it as ashift=9 by default? Isn't that configuration pool-specific? I wasn't even aware that you could mix-and-match?), but adding `-o ashift=9` allowed me to start a replacement of the log device. Of course, I didn't want an SSD log with ashift=9, but I was still thinking it might be a way to allow me to actually remove it.

The next thing happening was the pool now going into a resilver (why resilver to replace a log device?) at crazy speeds (looks related to [this bug](https://github.com/zfsonlinux/zfs/issues/8639)):

```
pool: titanic
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
   continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Tue May 14 23:01:45 2019
   1.04T scanned at 1.63G/s, 1.04T issued at 1.63G/s, 22.4T total
   0B resilvered, 4.62% done, 0 days 03:43:47 to go
config:

   NAME                                        STATE     READ WRITE CKSUM
   titanic                                     DEGRADED     0     0     0
     raidz3-0                                  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX31DA------  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX51D4------  ONLINE       0     0     0
       wwn-0x5000000000000001                  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX61D5------  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX31D6------  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX31D6------  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WXK1E9------  ONLINE       0     0 17.1K
       scsi-SWD_Elements_SE_25FF_WX31D6------  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX31D6------  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX31D6------  ONLINE       0     0     0
       scsi-SWD_Elements_SE_25FF_WX71D6------  ONLINE       0     0     0
   logs
     replacing-1                               DEGRADED     0     0     0
       slog                                    ONLINE       0     0     0
```
EDIT NOTE: There's a couple of lines missing here at the end. I copied this from an O3X forum post I made before this one, and I have apparently made a bad copy. The actual output did include the original log device's GUID, which was `3470644392946588961` under the `logs > replacing-1` section. Just FYI.

This was yesterday, and it never really finished or actually resilvered anything. Today, I wanted to replace the device that is listing 17.1K checksum errors above, but after doing `sudo zpool replace titanic -o ashift=12 scsi-SWD_Elements_SE_25FF_WXK1E98EZ514 /dev/md127`, I was still stuck in this broken resilver loop. Though I think this is actually unrelated, so I should probably just stop talking about it. 

About the actual issue! :D I had to export the pool, remove the partition from the SSD for the new log device that was being replaced in, and re-import it to get it to not continue trying to "resilver it into the pool." Again, it didn't seem to actually be doing anything, but it was stuck in the resilvering loop.

The current status now is this:

```
  pool: titanic
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
	continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Wed May 15 14:58:51 2019
	806G scanned at 437M/s, 270G issued at 146M/s, 22.4T total
	24.6G resilvered, 1.18% done, 1 days 20:02:20 to go
config:

	NAME                                          STATE     READ WRITE CKSUM
	titanic                                       DEGRADED     0     0     0
	  raidz3-0                                    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX31DA8D612X    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX51D48ANJJE    ONLINE       0     0     0
	    wwn-0x5000000000000001                    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX61D583R8YJ    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX31D685NH4X    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX31D685N9PE    ONLINE       0     0     0
	    replacing-6                               ONLINE       0     0     0
	      scsi-SWD_Elements_SE_25FF_WXK1E98EZ514  ONLINE       0     0     0
	      md127                                   ONLINE       0     0     0  (resilvering)
	    scsi-SWD_Elements_SE_25FF_WX31D68C3HU2    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX31D68C32HZ    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX31D68RUL25    ONLINE       0     0     0
	    scsi-SWD_Elements_SE_25FF_WX71D686LYUZ    ONLINE       0     0     0
	logs
	  replacing-1                                 UNAVAIL      0     0     0  insufficient replicas
	    1847322803164150369                       UNAVAIL      0     0     0  was /dev/disk/by-partlabel/slog

errors: No known data errors
```

This resilvering is for the device I'm actually currently replacing, so just disregard that. It's running along nicely, and it's not the fact that the pool is resilvering right now that is causing me to not be able to remove the log device, because I've tried this for a long time now, with the pool being in a normal state.

My attempts at removing the log device now:

```
daniel@titanic ~ sudo zpool remove titanic replacing-1
cannot remove replacing-1: Mount encrypted datasets to replay logs.
```

Again, the pool is mounted, and writeable. 

```
daniel@titanic ~ sudo zpool remove titanic 1847322803164150369
cannot remove 1847322803164150369: operation not supported on this type of pool
```

I read a similar post online where the issue had to do with the log device being a mirror. This is not my case. The log device, when it was there, was just `/dev/sda4` on my SSD.

### Describe how to reproduce the problem
Not to sure. I don't have any more drives available to do something like this. But I hope the above description helps. I initially created the pool (on macOS with O3X 1.8.2) with `sudo zpool create -d -f -o ashift=12 -o feature@encryption=enabled -o feature@lz4_compress=enabled -o feature@async_destroy=enabled -o feature@bookmarks=enabled -o feature@device_removal=enabled -o feature@embedded_data=enabled -o feature@empty_bpobj=enabled -o feature@enabled_txg=enabled -o feature@extensible_dataset=enabled -o feature@hole_birth=enabled -o feature@obsolete_counts=enabled -o feature@spacemap_histogram=enabled -o feature@spacemap_v2=enabled -o feature@zpool_checkpoint=enabled -o feature@filesystem_limits=enabled -o feature@multi_vdev_crash_dump=enabled -o feature@edonr=enabled -o feature@sha512=enabled -o feature@skein=enabled -o feature@large_blocks=enabled -O atime=off -O compress=lz4 -O encryption=on -O keylocation=file:///zfskey-titanic -O keyformat=passphrase -O normalization=formD titanic raidz3 disk4 disk5  disk6 disk7 disk8 disk9 disk10 disk11 disk12 disk13 disk14`

### Include any warning/errors/backtraces from the system logs
I'm not sure exactly what to provide. Please let me know if I can provide anything.

Thank you! :D

**Comment by behlendorf** [comment]
@DanielSmedegaardBuus thanks for the clear description of the issue `zpool remove <pool> <log>` issue.  Is it possible that your pool contains zfs volumes?  Similar to filesystems these may also prevent you from removing the log device.

Regarding `ashift` it's actually set per top-level vdev.  So it may be different between the primary pool storage and the log device.

**Comment by DanielSmedegaardBuus** [comment]
Thank you, @behlendorf, for picking up my report :)

Good to know about the ashift caveat! I'll make sure to specify at least ashift=12 when adding new log and cache devices.

About volumes, then no. These are my current resources:
```
daniel@titanic ~ zfs list -t filesystem
NAME      USED  AVAIL     REFER  MOUNTPOINT
scratch  1.21T   561G     1.21T  /scratch
titanic  16.3T  11.9T     16.2T  /titanic

daniel@titanic ~ zfs list -t snapshot
NAME                               USED  AVAIL     REFER  MOUNTPOINT
titanic@1                         30.3G      -     3.24T  -
titanic@lifeboat1in               24.5M      -     4.43T  -
titanic@3-lifeboat5-in            1.14M      -     6.18T  -
titanic@4-lifeboat2-in             558K      -     7.93T  -
titanic@5-lifeboat3-in             674K      -     9.69T  -
titanic@6-lifeboat4-in            5.65M      -     11.4T  -
titanic@7-lifeboat6-in            2.36M      -     13.2T  -
titanic@8-lifeboat7-in-pls-chk    1.15M      -     14.9T  -
titanic@bblicenseincoming         3.98M      -     16.0T  -
titanic@resynced-lb8              1.63M      -     16.2T  -
titanic@resynced-lb7              1.43M      -     16.2T  -
titanic@resynced-lb6and4          2.16M      -     16.2T  -
titanic@resynced-lb3              1.04M      -     16.2T  -

daniel@titanic ~ zfs list -t volume
no datasets available
```

Could the snapshots perhaps play in here? I'll destroy them and try again.

(BTW: /scratch is a single-disk zpool for temp stuffs)

**Comment by DanielSmedegaardBuus** [comment]
Okay, so I destroyed all snapshots and tried again, but still no donut:

```
daniel@titanic ~ sudo zpool detach titanic replacing-1
cannot detach replacing-1: only applicable to mirror and replacing vdevs

daniel@titanic ~ sudo zpool detach titanic 1847322803164150369
cannot detach 1847322803164150369: no valid replicas

daniel@titanic ~ sudo zpool remove titanic replacing-1
cannot remove replacing-1: Mount encrypted datasets to replay logs.

daniel@titanic ~ sudo zpool remove titanic 1847322803164150369
cannot remove 1847322803164150369: operation not supported on this type of pool
```

Here's a zdb output in case it reveals anything:

```
titanic:
    version: 5000
    name: 'titanic'
    state: 0
    txg: 674112
    pool_guid: 16521893545764552695
    errata: 4
    hostname: 'titanic'
    com.delphix:has_per_vdev_zaps
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 16521893545764552695
        create_txg: 4
        children[0]:
            type: 'raidz'
            id: 0
            guid: 4659468024210879297
            nparity: 3
            metaslab_array: 49
            metaslab_shift: 38
            ashift: 12
            asize: 44001052327936
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 37
            children[0]:
                type: 'disk'
                id: 0
                guid: 441859027389969777
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX31---------part1'
                whole_disk: 1
                DTL: 66
                create_txg: 4
                com.delphix:vdev_zap_leaf: 38
            children[1]:
                type: 'disk'
                id: 1
                guid: 9280418592635397006
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX51---------part1'
                whole_disk: 1
                DTL: 75
                create_txg: 4
                com.delphix:vdev_zap_leaf: 39
            children[2]:
                type: 'disk'
                id: 2
                guid: 11180904176649316025
                path: '/dev/disk/by-id/wwn-0x5000000000000001-part1'
                whole_disk: 1
                DTL: 76
                create_txg: 4
                com.delphix:vdev_zap_leaf: 40
            children[3]:
                type: 'disk'
                id: 3
                guid: 12559400542100398552
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX61---------part1'
                whole_disk: 1
                DTL: 94
                create_txg: 4
                com.delphix:vdev_zap_leaf: 41
            children[4]:
                type: 'disk'
                id: 4
                guid: 2832683662629342739
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX31---------part1'
                whole_disk: 1
                DTL: 93
                create_txg: 4
                com.delphix:vdev_zap_leaf: 42
            children[5]:
                type: 'disk'
                id: 5
                guid: 6026478568833279879
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX31---------part1'
                whole_disk: 1
                DTL: 92
                create_txg: 4
                com.delphix:vdev_zap_leaf: 43
            children[6]:
                type: 'replacing'
                id: 6
                guid: 10229782760370588424
                whole_disk: 0
                create_txg: 4
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 6419303814572286035
                    path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WXK1---------part1'
                    whole_disk: 1
                    DTL: 270
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 263
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 2136406140341623360
                    path: '/dev/md127p1'
                    whole_disk: 1
                    DTL: 295
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 294
                    resilver_txg: 674001
            children[7]:
                type: 'disk'
                id: 7
                guid: 10176258574433560930
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX31---------part1'
                whole_disk: 1
                DTL: 90
                create_txg: 4
                com.delphix:vdev_zap_leaf: 45
            children[8]:
                type: 'disk'
                id: 8
                guid: 189953569063301903
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX31---------part1'
                whole_disk: 1
                DTL: 89
                create_txg: 4
                com.delphix:vdev_zap_leaf: 46
            children[9]:
                type: 'disk'
                id: 9
                guid: 11557892718334905015
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX31---------part1'
                whole_disk: 1
                DTL: 88
                create_txg: 4
                com.delphix:vdev_zap_leaf: 47
            children[10]:
                type: 'disk'
                id: 10
                guid: 7385876886247550529
                path: '/dev/disk/by-id/scsi-SWD_Elements_SE_25FF_WX71---------part1'
                whole_disk: 1
                DTL: 87
                create_txg: 4
                com.delphix:vdev_zap_leaf: 48
        children[1]:
            type: 'replacing'
            id: 1
            guid: 5739250105803886075
            whole_disk: 0
            metaslab_array: 99
            metaslab_shift: 29
            ashift: 9
            asize: 17175150592
            is_log: 1
            create_txg: 32757
            com.delphix:vdev_zap_top: 98
            children[0]:
                type: 'disk'
                id: 0
                guid: 3470644392946588961
                path: '/private/var/run/disk/by-id/media-381A6E28-4FBC-487F-B6E1-F4E82C79D83F'
                whole_disk: 0
                not_present: 1
                DTL: 177
                create_txg: 32757
                com.delphix:vdev_zap_leaf: 97
            children[1]:
                type: 'disk'
                id: 1
                guid: 1847322803164150369
                path: '/dev/disk/by-partlabel/slog'
                whole_disk: 0
                not_present: 1
                DTL: 388
                create_txg: 32757
                com.delphix:vdev_zap_leaf: 288
                resilver_txg: 672507
    features_for_read:
        com.delphix:embedded_data
        com.delphix:hole_birth
```

BTW: Those dashes in the device names are from me redacting serial numbers. Not sure if that's just paranoid, it just seems like most people do that, so I'm following suit :)
