### ISSUE TITLE
autoreplace not working correctly with ZFS 0.8.x

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#10577]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7.8
Linux Kernel	| 3.10.0-1127.10.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1

### Describe the problem you're observing
autoreplacing is not working correctly on ZFS 0.8.x: when inserting a new blank disk, `zpool status` show the device as `UNAVAIL`. `zed` is running and `autoreplace=on`. To start the resilver, one as to export/import the pool or manually run a `zpool replace`. Using WWN/id/sd* names make no difference.

Debugging the issue, I found the following zfs events:
```
TIME                           CLASS
Jul 13 2020 18:16:18.069000000 sysevent.fs.zfs.history_event
Jul 13 2020 18:16:18.127000000 sysevent.fs.zfs.config_sync
Jul 13 2020 18:16:18.127000000 sysevent.fs.zfs.pool_import
Jul 13 2020 18:16:18.131000000 sysevent.fs.zfs.history_event
Jul 13 2020 18:16:18.213000000 sysevent.fs.zfs.config_sync
Jul 13 2020 18:16:40.553502714 resource.fs.zfs.statechange <--- remove
Jul 13 2020 18:16:40.622501866 sysevent.fs.zfs.config_sync
Jul 13 2020 18:17:15.479073873 resource.fs.zfs.statechange <--- attach
Jul 13 2020 18:17:15.496073664 sysevent.fs.zfs.vdev_online
Jul 13 2020 18:17:15.558072903 sysevent.fs.zfs.config_sync

```
ZED debug:
```
zed_disk_event:
        class: EC_dev_add
        subclass: disk
        dev_name: /dev/sdb
        path: /devices/pci0000:00/0000:00:02.6/0000:07:00.0/virtio5/host0/target0:0:0/0:0:0:1/block/sdb
        devid: scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-1
        phys_path: pci-0000:07:00.0-scsi-0:0:0:1
        dev_size: 2147483648
zfs_slm_event: EC_dev_add.disk
zfs_deliver_add: adding scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-1 (pci-0000:07:00.0-scsi-0:0:0:1) (is_slice 0)
zfs_iter_pool: evaluating vdevs on tank (by devid)
zfs_iter_pool: evaluating vdevs on tank (by phys_path)
  zfs_iter_vdev: matched phys_path on pci-0000:07:00.0-scsi-0:0:0:1
zfs_process_add: pool 'tank' vdev '/dev/disk/by-path/pci-0000:07:00.0-scsi-0:0:0:1-part1', phys 'pci-0000:07:00.0-scsi-0:0:0:1' wholedisk 1, dm 0 (7228918098681742888)
```

It seems that the problem lies in the missing partition (part1) on the newly inserted disk. In other words, ZED tries to bring the vdev online *before* creating the required *-part1 block device. In turn ZFS detect the missing partition/block device and report it as `UNAVAIL`.

By comparison, these are the zpool events logged on an otherwise identical VM with CentOS 7.7 and ZFS 0.7.13:
```
TIME                           CLASS
Jul 13 2020 18:01:04.958000000 sysevent.fs.zfs.history_event
Jul 13 2020 18:01:05.054000000 sysevent.fs.zfs.config_sync
Jul 13 2020 18:01:05.054000000 sysevent.fs.zfs.pool_import
Jul 13 2020 18:01:05.062000000 sysevent.fs.zfs.history_event
Jul 13 2020 18:01:05.175000000 sysevent.fs.zfs.config_sync
Jul 13 2020 18:05:55.190363080 ereport.fs.zfs.io           <--- remove
Jul 13 2020 18:05:55.190363080 ereport.fs.zfs.io
Jul 13 2020 18:05:55.190363080 ereport.fs.zfs.io
Jul 13 2020 18:05:55.190363080 ereport.fs.zfs.probe_failure
Jul 13 2020 18:05:55.257362073 ereport.fs.zfs.vdev.too_small
Jul 13 2020 18:05:55.257362073 resource.fs.zfs.statechange
Jul 13 2020 18:07:29.741645829 sysevent.fs.zfs.config_sync <--- attach
Jul 13 2020 18:07:29.875643033 resource.fs.zfs.statechange
Jul 13 2020 18:07:29.930641886 resource.fs.zfs.statechange
Jul 13 2020 18:07:29.993640572 sysevent.fs.zfs.config_sync
Jul 13 2020 18:07:30.024639925 sysevent.fs.zfs.vdev_attach
Jul 13 2020 18:07:30.116638006 sysevent.fs.zfs.resilver_start
Jul 13 2020 18:07:30.116638006 sysevent.fs.zfs.history_event
Jul 13 2020 18:07:30.788623987 sysevent.fs.zfs.history_event
Jul 13 2020 18:07:30.788623987 sysevent.fs.zfs.resilver_finish
Jul 13 2020 18:07:30.792623903 sysevent.fs.zfs.config_sync
Jul 13 2020 18:07:30.907621504 sysevent.fs.zfs.vdev_remove
Jul 13 2020 18:07:30.909621463 sysevent.fs.zfs.history_event
Jul 13 2020 18:07:30.986619856 sysevent.fs.zfs.config_sync
Jul 13 2020 18:07:35.907517196 sysevent.fs.zfs.history_event

```
As you can see, there are many more events (and vdev_attach sounds as a obvious thing missing from the reported ZFS 0.8.4 events).

Any suggestion?
Thanks. 

### Describe how to reproduce the problem

1. create a simple mirrored pool with a single top-level vdev
2. detach a disk from the system
3. `zpool status` show the disk as `OFFLINE` (it was `zed` which offlined the removed disk)
4. insert a new blank disk (or the same disk after being wiped on another system)
5. `zpool status` now show the disk as `UNAVAIL`
6. to start resilver, one has to manually export/import the pool or issue `zpool replace`
