### ISSUE TITLE
ZFS Channel Programs cannot get_prop `encryption` or `encryptionroot` properties

### ISSUE THREAD

**Issue by grahamc** [openzfs/zfs#12337]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| NixOS
Distribution Version	| 21.09 (unstable)
Linux Kernel	|  5.10.45
Architecture	| x86_64
ZFS Version	| 2.1.0-1
SPL Version	| 2.1.0-1

and by @nshalman:

Type | Version/Name
 --- | ---
Distribution Name	| SmartOS
Distribution Version	| joyent_20210520T001536Z
Architecture	| x86_64

### Describe the problem you're observing

A ZFS Channel Program can't access, seemingly, just these two properties:

enc.lua:

```lua
dataset = "tank/safe/home"

result = {}
result["keyformat"] = zfs.get_prop(dataset, "keyformat")
result["keylocation"] = zfs.get_prop(dataset, "keylocation")
result["encryption"] = zfs.get_prop(dataset, "encryption")
result["encryptionroot"] = zfs.get_prop(dataset, "encryptionroot") == null
return result
```

results in:

```console
grahamc@hyperchicken:~/ > zfs get encryption tank/safe/home
NAME            PROPERTY    VALUE        SOURCE
tank/safe/home  encryption  aes-256-gcm  -

grahamc@hyperchicken:~/ > zfs get encryptionroot tank/safe/home
NAME            PROPERTY        VALUE    SOURCE
tank/safe/home  encryptionroot  tank     -

grahamc@hyperchicken:~/ > sudo zfs program tank ./enc.lua
Channel program fully executed and produced output:
    return:
        encryptionroot: true
        encryption: 'off'
        keylocation: 'none'
        keyformat: 'passphrase'
```

and for @nshalman:

```
# echo "passphrase" | zfs create -o encryption=aes-256-ccm -o keyformat=passphrase zones/deleteme
# zfs get all zones/deleteme | grep cryp
zones/deleteme  encryption            aes-256-ccm            -
zones/deleteme  encryptionroot        zones/deleteme         -
# zfs program zones ./enc.lua
Channel program fully executed and produced output:
    return:
        encryptionroot: true
        keyformat: 'none'
        keylocation: 'prompt'
        encryption: 'off'
```

### Describe how to reproduce the problem

Create an encrypted dataset:

```
echo "passphrase" | zfs create -o encryption=aes-256-ccm -o keyformat=passphrase zones/deleteme
```

then edit `enc.lua` from above to point to the dataset and execute it, note the `encryption` and `encryptionroot` fields are not correctly reported.

### Include any warning/errors/backtraces from the system logs

none

---

I've opened PR #12335 adding a test to verify channel programs can access these two fields. As expected, the test fails in the [sanity tests](https://github.com/openzfs/zfs/pull/12335/checks?check_run_id=3019832976):

```
Test: /usr/share/zfs/zfs-tests/tests/functional/channel_program/lua_core/tst.encryption (run as root) [00:00] [FAIL]
```
