### ISSUE TITLE
ZFS will not accept ashift override on replace command

### ISSUE THREAD

**Issue by Heebie** [openzfs/zfs#1328]
command issued initially, and resulting error:

```
# zpool replace -f zstorpool /dev/disk/by-id/scsi-SATA_ST32000542AS_5XW16V0D /dev/disk/by-id/scsi-SATA_ST2000DM001-1CH_S1E1A0BA
cannot replace /dev/disk/by-id/scsi-SATA_ST32000542AS_5XW16V0D with /dev/disk/by-id/scsi-SATA_ST2000DM001-1CH_S1E1A0BA: devices have different sector alignment
```

Alternate commands tried after consultation with ryao on #ZFS at irc.freenode.net and resulting errors

```
# zpool replace -f zstorpool -o ashift=9 /dev/disk/by-id/scsi-SATA_ST32000542AS_5XW16V0D /dev/disk/by-id/scsi-SATA_ST2000DM001-1CH_S1E1A0BA

cannot replace /dev/disk/by-id/scsi-SATA_ST32000542AS_5XW16V0D with /dev/disk/by-id/scsi-SATA_ST2000DM001-1CH_S1E1A0BA: devices have different sector alignment

# zpool replace -o ashift=9 -f zstorpool 16614678759998795105 /dev/disk/by-id/scsi-SATA_ST2000DM001-1CH_S1E1A0BA

cannot replace 16614678759998795105 with /dev/disk/by-id/scsi-SATA_ST2000DM001-1CH_S1E1A0BA: devices have different sector alignment
```

zdb output: 

```
zstorpool:
    version: 28
    name: 'zstorpool'
    state: 0
    txg: 749628
    pool_guid: 17936043063974742421
    hostname: 'zdesk'
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 17936043063974742421
        children[0]:
            type: 'raidz'
            id: 0
            guid: 14522715789141641327
            nparity: 1
            metaslab_array: 30
            metaslab_shift: 36
            ashift: 9
            asize: 8001538752512
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 16614678759998795105
                path: '/dev/disk/by-id/scsi-SATA_ST32000542AS_5XW16V0D-part1'
                whole_disk: 1
                DTL: 131
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 16061998313616699468
                path: '/dev/disk/by-id/scsi-1AMCC_6XW1R0DH000000000000-part1'
                whole_disk: 1
                DTL: 201
                create_txg: 4
            children[2]:
                type: 'disk'
                id: 2
                guid: 7107043616282400247
                path: '/dev/disk/by-id/scsi-1AMCC_Z1E10TJP000000000000-part1'
                whole_disk: 1
                DTL: 213
                create_txg: 4
            children[3]:
                type: 'disk'
                id: 3
                guid: 17736576476345012069
                path: '/dev/disk/by-id/scsi-SATA_ST2000DM001-9YN_Z1E0ZMKY-part1'
                whole_disk: 1

                DTL: 228
                create_txg: 4
        children[1]:
            type: 'mirror'
            id: 1
            guid: 6794649090136988505
            metaslab_array: 65
            metaslab_shift: 24
            ashift: 9
            asize: 3216506880
            is_log: 1
            create_txg: 50921
            children[0]:
                type: 'disk'
                id: 0
                guid: 1540290791449404783
                path: '/dev/disk/by-id/scsi-SATA_OCZ-AGILITY3_OCZ-ZEDTKKYOQ1S1MWWP-part6'
                whole_disk: 0
                DTL: 198
                create_txg: 50921
            children[1]:
                type: 'disk'
                id: 1
                guid: 15641546974276719667
                path: '/dev/disk/by-id/scsi-SATA_OCZ-AGILITY3_OCZ-00RE40B32QZHBQW3-part6'
                whole_disk: 0
                DTL: 197
                create_txg: 50921
```

Software versions, Ubuntu Linux 12.04

ii  dkms                                   2.2.0.3-1ubuntu3.1+zfs5~precise1        Dynamic Kernel Module Support Framework
ii  libzfs1                                0.6.0.97-0ubuntu1~precise1              Native ZFS filesystem library for Linux
ii  mountall                               2.36.4-zfs1                             filesystem mounting tool
ii  ubuntu-zfs                             7~precise                               Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-dkms                               0.6.0.97-0ubuntu1~precise1              Native ZFS filesystem kernel modules for Linux
ii  zfsutils                               0.6.0.97-0ubuntu1~precise1              Native ZFS management utilities for Linux
