### ISSUE TITLE
zpool remove of top-level mirror or vdev still no work

### ISSUE THREAD

**Issue by haraldrudell** [openzfs/zfs#13552]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04 focal
Kernel Version	| 5.13.0-41-generic
Architecture	| amd64
OpenZFS Version	| zfs-2.1.4-0york0~20.04, zfs-kmod-2.0.6-1ubuntu2.1

### Describe the problem you're observing

**zpool remove** errors despite documented requirements apparently fulfilled

### Describe how to reproduce the problem

use my pool… 
zfs provides no ability for more detail, any log or any helpful error messages

For example, zfs could tell me how many more bytes I need, right?

### Include any warning/errors/backtraces from the system logs

I am trying to migrate a pool from disk to partition

* with usb, disks may come back under a new /dev/sd name, so if vdevs are not partitions, a reboot is required

To remove a top-level mirror or simple vdev (I tried both) ashift must be same, no raidz, encryption keys loaded
* The error message for no encryption key is still the unhelpful “permission denied”

THE ERROR
```
date --rfc-3339=second && zpool remove zro b7f9667a-343c-4fec-aeb1-2ed5fd9f7319
2022-06-13 00:01:00-07:00
cannot remove b7f9667a-343c-4fec-aeb1-2ed5fd9f7319: out of space
```

THE FACTS
```
zdb -C zro | less
path: '/dev/disk/by-partuuid/b7f9667a-343c-4fec-aeb1-2ed5fd9f7319'
ashift: 16
asize: 2000384688128
path: '/dev/disk/by-partuuid/202d6b64-987c-406d-b64e-81e6357a9721'
ashift: 16
asize: 2000393076736
```
NOTE: 202d… is apparently larger than b7f9…

```
zpool list -poalloc zro
        ALLOC
1828179083264
```

HERE’S THE SIZE OF 202d… as a POOL:
```
zpool list -posize zrw220612
         SIZE
1992864825344
```

APPARENT SPACE AVAILABLE:
1992864825344 - 1828179083264 = 164685742080 bytes ≈ 153 GiB

PERCENTAGE SPACE AVAILABLE:
164685742080 / 1992864825344 ≈ 8.2%

#11409 lists some apparently undocumented requirements

#11356 have some more

Because the second device is actually larger, this is probably some other buggy bug hiding behind the out of space error

I noticed you lose about 16 GiB by going to partition from full disk

**zdb -C** also lists 3 indirect devices that should be removable using **zfs remap** That command is not available

**Comment by rincebrain** [comment]
Well, you're running ZFS 2.0.6 kernel modules with ZFS 2.1.4 userland, so surprising things may ensue. Did you install jonathonf's PPA but not install the zfs-dkms package with the others, maybe? That's usually what happened when I see that.

It would be helpful if you included the (full, not just the parts you think are relevant) output of `zpool list -vp` on the pool you're trying `zpool remove` on.

Finally, an -f to override the space checks would be a very bad idea, IMO - people wouldn't bother reporting issues or investigating why it refused, they'd just start using -f, and then complain when it broke midway through if they did, indeed, not have sufficient space.

(`zfs remap` was removed in 6e91a72fe3ff8bb282490773bd687632f3e8c79d, but also didn't do what you seem to think it does - it forced the remapping of specific things you used `zpool remove` on immediately, but it did not delete indirect vdevs entirely; those will, as far as I know, never go away for the lifetime of the pool, they just don't get shown, and the indirection table for each will eventually be empty, ideally.)

**Comment by haraldrudell** [comment]
Retried with fresh install
Ubuntu 22.04 jammy
5.13.0-48-generic
zfs-2.1.2-1ubuntu3 zfs-kmod-2.0.6-1ubuntu2.1

same FAIL outcome

```
zpool list -vp zro
NAME                                             SIZE          ALLOC           FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
zro                                     3985729650688  1828179083264  2157550567424        -         -      3     45   1.00    ONLINE  -
  b7f9667a-343c-4fec-aeb1-2ed5fd9f7319  1992864825344  1828145594368  164719230976        -         -      6     91      -    ONLINE
  202d6b64-987c-406d-b64e-81e6357a9721  1992864825344  33488896  1992831336448        -         -      0      0      -    ONLINE
```

**Comment by rincebrain** [comment]
That's the same kind of mismatched kernel module version as before, and 22.04 doesn't ship that kernel version, so I think you installed something else.

**Comment by haraldrudell** [comment]
Fixed that, too: unfortunately still there. I will try the second pool, too

```
date --rfc-3339=second && zpool remove zro b7f9667a-343c-4fec-aeb1-2ed5fd9f7319
2022-06-15 03:21:18-07:00
cannot remove b7f9667a-343c-4fec-aeb1-2ed5fd9f7319: out of space
zpool list -vp zro
NAME                                             SIZE          ALLOC           FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
zro                                     3985729650688  1828159422464  2157570228224        -         -      3     45   1.00    ONLINE  -
  b7f9667a-343c-4fec-aeb1-2ed5fd9f7319  1992864825344  1828139237376  164725587968        -         -      6     91      -    ONLINE
  202d6b64-987c-406d-b64e-81e6357a9721  1992864825344  20185088  1992844640256        -         -      0      0      -    ONLINE
```


```
echo $(date --rfc-3339=second) $(hostname -s) $(lsb_release --codename --release --short) $(uname --kernel-release) $(uptime --since) && echo $(zfs version)
2022-06-15 03:21:32-07:00 c68z 22.04 jammy 5.15.0-37-generic 2022-06-15 01:57:46
zfs-2.1.2-1ubuntu3 zfs-kmod-2.1.2-1ubuntu3
```

**Comment by haraldrudell** [comment]
The purpose of this exercise was to change the vdevs from being whole disk to instead the single partition on that same disk.
I expected the vdevs to shrink by this, but it turns out vdevs are enlarged by about 9 GiB.
Expecting vdevs to shrink, this is why I used striping on the first pool, causing the trouble.
The second pool, now knowing vdevs are enlarging, I used a single top-level mirror and then resized online to vdev, so that worked.
For the first pool, it is still the case that the second stripe cannot be removed, but there are still activities resolvering that may work.

Unexpectedly, I could add a smaller device to the first stripe making it a mirror. It appears zfs is confused about vdev sizes
If I understand this right, some vdevs are both current and indirect.


The goal below is for zro to consist of the single vdev 202d6b64

```
date --rfc-3339=second && zpool status zro                                                                 
2022-06-15 11:18:24-07:00                                                                                                   
  pool: zro                                                                                                                 
 state: ONLINE                                                                                                              
status: One or more devices is currently being resilvered.  The pool will                                                   
        continue to function, possibly in a degraded state.                                                                 
action: Wait for the resilver to complete.                                                                                  
  scan: resilver in progress since Wed Jun 15 11:10:25 2022                                                                 
        1.66T scanned at 3.55G/s, 71.4G issued at 153M/s, 1.66T total                                                       
        74.1G resilvered, 4.19% done, 03:02:29 to go                                                                        
remove: Removal of vdev 2 copied 8.25M in 0h0m, completed on Sat Jun 11 11:36:35 2022                                       
        2.98K memory used for removed device mappings                                                                       
config:                                                                                                                     
                                                                                                                            
        NAME                                      STATE     READ WRITE CKSUM                                                
        zro                                       ONLINE       0     0     0                                                
          mirror-0                                ONLINE       0     0     0                                                
            b7f9667a-343c-4fec-aeb1-2ed5fd9f7319  ONLINE       0     0     0                                                
            202d6b64-987c-406d-b64e-81e6357a9721  ONLINE       0     0     0  (resilvering)                                 
          692da33c-0f8e-47ff-a7bf-8d6770772469    ONLINE       0     0     0                                                
                                                                                                                            
errors: No known data errors                                                                                                
```

```
zdb -C zro                                                                                                 
                                                                                                                            
MOS Configuration:                                                                                                          
        version: 5000
        name: 'zro'
        state: 0
        txg: 13168461
        pool_guid: 14578202207106007368
        errata: 0
        hostid: 1532761246
        hostname: 'c68z'
        com.delphix:has_per_vdev_zaps
        vdev_children: 5
        vdev_tree:
            type: 'root'
            id: 0
            guid: 14578202207106007368
            create_txg: 4
            children[0]:
                type: 'mirror'
                id: 0
                guid: 5986449157720229279
                whole_disk: 0
                metaslab_array: 136
                metaslab_shift: 34
                ashift: 16
                asize: 2000384688128
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 135
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 4608714181282964506
                    path: '/dev/disk/by-partuuid/b7f9667a-343c-4fec-aeb1-2ed5fd9f7319'
                    whole_disk: 0
                    DTL: 531
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 529
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 10232177178490955932
                    path: '/dev/disk/by-partuuid/202d6b64-987c-406d-b64e-81e6357a9721'
                    whole_disk: 0
                    DTL: 2489
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 2406
                    resilver_txg: 13168458
            children[1]:
                type: 'indirect'
                id: 1
                guid: 2079469523163655316
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 34
                ashift: 16
                asize: 2000393076736
                create_txg: 4
                com.delphix:vdev_zap_top: 135
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 4608714181282964506
                    path: '/dev/disk/by-partuuid/b7f9667a-343c-4fec-aeb1-2ed5fd9f7319'
                    whole_disk: 0
                    DTL: 531
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 529
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 10232177178490955932
                    path: '/dev/disk/by-partuuid/202d6b64-987c-406d-b64e-81e6357a9721'
                    whole_disk: 0
                    DTL: 2489
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 2406
                    resilver_txg: 13168458
            children[1]:
                type: 'indirect'
                id: 1
                guid: 2079469523163655316
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 34
                ashift: 16
                asize: 2000393076736
                is_log: 0                                                                                                   
                com.delphix:indirect_object: 324                                                                            
                com.delphix:indirect_births: 326                                                                            
                create_txg: 13144933                                                                                        
                com.delphix:vdev_zap_top: 5                                                                                 
            children[2]:                                                                                                    
                type: 'indirect'                                                                                            
                id: 2                                                                                                       
                guid: 17684715946461903184                                                                                  
                whole_disk: 0                                                                                               
                metaslab_array: 0                                                                                           
                metaslab_shift: 34                                                                                          
                ashift: 16                                                                                                  
                asize: 2010039975936                                                                                        
                is_log: 0
                com.delphix:indirect_object: 15
                com.delphix:indirect_births: 17
                com.delphix:prev_indirect_vdev: 3
                create_txg: 13145756
                com.delphix:vdev_zap_top: 396
            children[3]:
                type: 'indirect'
                id: 3
                guid: 11721561378520130680
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 34
                ashift: 16
                asize: 2000393076736
                is_log: 0
                com.delphix:indirect_object: 176
                com.delphix:indirect_births: 178
                com.delphix:prev_indirect_vdev: 1
                create_txg: 13146201
                com.delphix:vdev_zap_top: 525
            children[4]:
                type: 'disk'
                id: 4
                guid: 4756522072335310867
                path: '/dev/disk/by-partuuid/692da33c-0f8e-47ff-a7bf-8d6770772469'
                whole_disk: 0
                metaslab_array: 405
                metaslab_shift: 34
                ashift: 16
                asize: 2000393076736
                is_log: 0
                DTL: 518
                create_txg: 13146842
                com.delphix:vdev_zap_leaf: 395
                com.delphix:vdev_zap_top: 399
        features_for_read:
            com.delphix:hole_birth
            com.delphix:embedded_data
            com.delphix:device_removal
```
