### ISSUE TITLE
zpool scrub only scans the special vdev

### ISSUE THREAD

**Issue by speed47** [openzfs/zfs#13706]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 22.04
Kernel Version	| 5.15.53 (vanilla)
Architecture	| x86_64
OpenZFS Version	| 2.0.0 - 2.1.99 (commit 34aa0f0487705671c81262adb7646a90d15c5a12)

### Describe the problem you're observing
When running a `zpool scrub` on a zpool with 2 (data) mirrors with HDDs and one special mirror with SSDs, only the special mirror seems to be scanned, as can be seen below:

```
# zpool status z
  pool: z
 state: ONLINE
status: Some supported and requested features are not enabled on the pool.
        The pool can still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(7) for details.
  scan: scrub in progress since Fri Jul 29 19:30:18 2022
        817G scanned at 51.1G/s, 817G issued at 51.1G/s, 12.8T total
        0B repaired, 6.21% done, 00:04:01 to go
remove: Removal of vdev 7 copied 38.6G in 0h7m, completed on Fri Jul 29 11:01:51 2022
        2.11M memory used for removed device mappings
config: 

        NAME                                           STATE     READ WRITE CKSUM
        z                                              ONLINE       0     0     0
          mirror-0                                     ONLINE       0     0     0
            usb-WD_Elements_25A3_35514747344C4242-0:0  ONLINE       0     0     0
            ata-WDC_WD120EDAZ-11F3RA0_5PG63E9F         ONLINE       0     0     0
          mirror-1                                     ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2DVRDXF   ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2STUCVR   ONLINE       0     0     0
        special
          mirror-9                                     ONLINE       0     0     0
            vgssd1000/z_special_ssd1000                ONLINE       0     0     0
            vg/z_special_ssd300                        ONLINE       0     0     0
```

The status line `817G scanned at 51.1G/s, 817G issued at 51.1G/s, 12.8T total` progresses very fast, and the amount scanned and issued are always exactly the same, up to 12.8T after less than 5 minutes when the scrub is considered complete, and obviously none of the HDDs have actually scanned their blocks.
This can also be confirmed running `iostat -x 1` in parallel: only the SSD disks are actively working, the others are mostly idle.

### Describe how to reproduce the problem
This is reproducible 100% of the time, at least with my zpool setup: I have no way to actually scrub the data (AFAICT)
The setup details can be found below. It should be noted that there were a few add/remove/attach/detach operations on the special vdevs, which implies that there are several indirect vdevs (as can be seen in the `zdb -C` dump).
The pool has been created under v2.1.5 with `-o ashift=12 -o feature@encryption=enabled`

<details>
  <summary>zpool list -v</summary>

```
  NAME                                            SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
z                                              13.7T  12.8T   893G        -         -     0%    93%  1.00x    ONLINE  -
  mirror-0                                     10.9T  10.1T   805G        -         -     0%  92.8%      -    ONLINE
    usb-WD_Elements_25A3_35514747344C4242-0:0  10.9T      -      -        -         -      -      -      -    ONLINE
    ata-WDC_WD120EDAZ-11F3RA0_5PG63E9F         10.9T      -      -        -         -      -      -      -    ONLINE
  mirror-1                                     2.72T  2.69T  27.7G        -         -     0%  99.0%      -    ONLINE
    ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2DVRDXF   2.73T      -      -        -         -      -      -      -    ONLINE
    ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2STUCVR   2.73T      -      -        -         -      -      -      -    ONLINE
special                                            -      -      -        -         -      -      -      -         -
  mirror-9                                     99.5G  39.0G  60.5G        -         -    10%  39.2%      -    ONLINE
    vgssd1000/z_special_ssd1000                 100G      -      -        -         -      -      -      -    ONLINE
    vg/z_special_ssd300                         100G      -      -        -         -      -      -      -    ONLINE
```

</details>

<details>
<summary>zdb -C</summary>

```
MOS Configuration:
        version: 5000
        name: 'z'
        state: 0
        txg: 191183
        pool_guid: 17784954522390314791
        errata: 0
        hostname: 'nas'
        com.delphix:has_per_vdev_zaps
        vdev_children: 10
        vdev_tree:
            type: 'root'
            id: 0
            guid: 17784954522390314791
            create_txg: 4
            children[0]:
                type: 'mirror'
                id: 0
                guid: 2972948471517465359
                metaslab_array: 65
                metaslab_shift: 34
                ashift: 12
                asize: 12000089866240
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 129
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 2886530369459906751
                    path: '/dev/disk/by-id/usb-WD_Elements_25A3_35514747344C4242-0:0-part1'
                    devid: 'usb-WD_Elements_25A3_35514747344C4242-0:0-part1'
                    phys_path: 'pci-0000:00:14.0-usb-0:4:1.0-scsi-0:0:0:0'
                    whole_disk: 1
                    DTL: 800
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 130
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 4718213307199790485
                    path: '/dev/disk/by-id/ata-WDC_WD120EDAZ-11F3RA0_5PG63E9F-part1'
                    devid: 'ata-WDC_WD120EDAZ-11F3RA0_5PG63E9F-part1'
                    phys_path: 'pci-0000:00:1f.2-ata-5.0'
                    whole_disk: 1
                    DTL: 799
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 131
            children[1]:
                type: 'mirror'
                id: 1
                guid: 1012032482718870771
                metaslab_array: 79
                metaslab_shift: 34
                ashift: 12
                asize: 3000578342912
                is_log: 0
                create_txg: 13
                com.delphix:vdev_zap_top: 385
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 9926059460638940645
                    path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2DVRDXF-part1'
                    devid: 'ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2DVRDXF-part1'
                    phys_path: 'pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0'
                    whole_disk: 1
                    DTL: 798
                    create_txg: 13
                    com.delphix:vdev_zap_leaf: 386
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 1153354702596158308
                    path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2STUCVR-part1'
                    devid: 'ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N2STUCVR-part1'
                    phys_path: 'pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:1'
                    whole_disk: 1
                    DTL: 797
                    create_txg: 13
                    com.delphix:vdev_zap_leaf: 387
            children[2]:
                type: 'indirect'
                id: 2
                guid: 6093511207376287821
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 29
                ashift: 12
                asize: 21470117888
                is_log: 0
                com.delphix:indirect_object: 73129
                com.delphix:indirect_births: 73131
                create_txg: 37
                com.delphix:vdev_zap_top: 390
            children[3]:
                type: 'indirect'
                id: 3
                guid: 17247912709748369651
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 29
                ashift: 12
                asize: 21470117888
                is_log: 0
                com.delphix:indirect_object: 72946
                com.delphix:indirect_births: 72948
                com.delphix:prev_indirect_vdev: 2
                create_txg: 37
                com.delphix:vdev_zap_top: 392
            children[4]:
                type: 'indirect'
                id: 4
                guid: 17978966862030276124
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 29
                ashift: 12
                asize: 48313663488
                is_log: 0
                com.delphix:indirect_object: 73354
                com.delphix:indirect_births: 73356
                com.delphix:prev_indirect_vdev: 3
                create_txg: 72529
                com.delphix:vdev_zap_top: 72667
            children[5]:
                type: 'indirect'
                id: 5
                guid: 3364556388247222535
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 29
                ashift: 12
                asize: 42944954368
                is_log: 0
                non_allocating: 1
                com.delphix:indirect_object: 1457
                com.delphix:indirect_births: 1460
                com.delphix:prev_indirect_vdev: 4
                create_txg: 72694
                com.delphix:vdev_zap_top: 73085
            children[6]:
                type: 'indirect'
                id: 6
                guid: 9730150406886455653
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 29
                ashift: 12
                asize: 53682372608
                is_log: 0
                non_allocating: 1
                com.delphix:indirect_object: 6134
                com.delphix:indirect_births: 6136
                com.delphix:prev_indirect_vdev: 5
                create_txg: 176839
                com.delphix:vdev_zap_top: 675
            children[7]:
                type: 'indirect'
                id: 7
                guid: 10676060885641407609
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 29
                ashift: 12
                asize: 107369463808
                is_log: 0
                non_allocating: 1
                com.delphix:indirect_object: 7466
                com.delphix:indirect_births: 7468
                com.delphix:prev_indirect_vdev: 8
                create_txg: 184452
                com.delphix:vdev_zap_top: 6124
            children[8]:
                type: 'indirect'
                id: 8
                guid: 11608273382032491262
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 29
                ashift: 12
                asize: 53682372608
                is_log: 0
                non_allocating: 1
                com.delphix:indirect_object: 7362
                com.delphix:indirect_births: 7364
                com.delphix:prev_indirect_vdev: 6
                create_txg: 184997
                com.delphix:vdev_zap_top: 7358
            children[9]:
                type: 'mirror'
                id: 9
                guid: 6572754825354807752
                metaslab_array: 7252
                metaslab_shift: 29
                ashift: 12
                asize: 107369463808
                is_log: 0
                create_txg: 185045
                com.delphix:vdev_zap_top: 7154
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 18412959171612156138
                    path: '/dev/vgssd1000/z_special_ssd1000'
                    whole_disk: 0
                    DTL: 8113
                    create_txg: 185045
                    com.delphix:vdev_zap_leaf: 7155
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 14761859464850297329
                    path: '/dev/vg/z_special_ssd300'
                    whole_disk: 0
                    DTL: 8112
                    create_txg: 185045
                    com.delphix:vdev_zap_leaf: 7156
        features_for_read:
            com.delphix:hole_birth
            com.delphix:embedded_data
            com.delphix:device_removal
```

</details>

### Include any warning/errors/backtraces from the system logs

None.
