### ISSUE TITLE
zpool half-unavail after power loss

### ISSUE THREAD

**Issue by Ukko-Ylijumala** [openzfs/zfs#1390]
After a power loss event client's zpool has become kind-of faulted due to half of the pool being in "UNAVAIL" state, even though the disks are all there physically. Here's what `zpool import` has to say about the pool:

```
root@zfs:/dev/disk# zpool import
   pool: arkisto
     id: 4276253443581125741
  state: ONLINE
 status: One or more devices contains corrupted data.
 action: The pool can be imported using its name or numeric identifier.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 config:

        arkisto       ONLINE
          raidz2-0    ONLINE
            c3e1d01   ONLINE
            c3e1d02   ONLINE
            c3e1d03   ONLINE
            c3e1d04   ONLINE
            c3e1d05   ONLINE
            c3e1d06   ONLINE
            c3e1d07   ONLINE
            c3e1d08   ONLINE
            c3e1d09   ONLINE
            c3e1d10   ONLINE
          raidz2-2    ONLINE
            c3e1d11   UNAVAIL  corrupted data
            c3e1d12   UNAVAIL  corrupted data
            c3e1d13   UNAVAIL  corrupted data
            c3e1d14   UNAVAIL  corrupted data
            c3e1d15   UNAVAIL  corrupted data
            c3e1d16   UNAVAIL  corrupted data
            c3e1d17   UNAVAIL  corrupted data
            c3e1d18   UNAVAIL  corrupted data
            c3e1d19   UNAVAIL  corrupted data
            c3e1d20   UNAVAIL  corrupted data
        cache
          ssd1-part2
          ssd2-part2
          ssd3-part2
          ssd4-part2
        spares
          c3e1d21
        logs
          zil-part1   ONLINE
```

The pool was made with ZoL rc-12 with 10 devices (raidz2-0), slog and 4x caches. A month or 2 later zfs was upgraded to rc-13 and the 2nd raidz2 vdev + spare was added. This difference will become noticeable when looking at the zdb outputs later. After the power loss today zfs was upgraded to latest master.

The disk names have been simplified with vdev_id.conf. Trying to import with `zpool import -d /dev/disk/by-id/` causes exactly the same UNAVAIL state on the 2nd vdev, so vdev_id.conf is correctly formatted. Also udev creates the symlinks as they should be, so there's no issue there either. Here is the relevant section of the file: http://pastebin.com/KRM65YPh

zdb sees all labels on all disks, and they seem to decode correctly.

zdb -l /dev/disk/by-vdev/c3e1d01-part1 (1st vdev): http://pastebin.com/Gt6BMYFL
zdb -l /dev/disk/by-vdev/c3e1d11-part1 (2nd vdev): http://pastebin.com/UpcTsMiZ

zdb -l from zil/slog says this:

```
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 28
    name: 'arkisto'
    state: 0
    txg: 1219593
    pool_guid: 4276253443581125741
    hostid: 168435210
    hostname: 'zfs'
    top_guid: 5371802998993008076
    guid: 5371802998993008076
    is_log: 1
    vdev_children: 3
    vdev_tree:
        type: 'disk'
        id: 1
        guid: 5371802998993008076
        path: '/dev/disk/zpool/zil-part1'
        whole_disk: 0
        metaslab_array: 81
        metaslab_shift: 25
        ashift: 9
        asize: 5363990528
        is_log: 1
        DTL: 84
        create_txg: 538529
```

Now, what on earth has happened? The pool was working correctly before the power loss. I've tried several symlink tricks, but none cause any difference. The disks are behind the same SAS controller+expander, so if either broke, I'd expect none of the disks to show up.

Trying an actual import in this state leads to the import getting to D state with 5x `z_wr_iss_h` threads stuck at 100% CPU and no I/O being done.

Looking at the txgs, the vdev with UNAVAIL disks is on 1219594, while slog and the other vdev are on 1219593.. could this be the cause?

Is there a reasonable chance that trying to import the pool with past transactions could restore a sane state? Can that be done with -o readonly?  A `zpool import -nfF arkisto` also hangs, so I can't get an estimate of what would be lost by rewinding.
