### ISSUE TITLE
Don`t silently increase ashift when creating pool

### ISSUE THREAD

**Issue by vaclavskala** [openzfs/zfs#14409]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04
Kernel Version	| 5.10.136
Architecture	| x86_64
OpenZFS Version	| utils 2.1.2, module 2.1.5

### Describe the problem you're observing
ZFS silently increase ashift when creating pool and than recordsize smaller than real ashift leads to space waste.

### Describe how to reproduce the problem
Created pool using this command
`zpool create -o ashift=12 -O acltype=posixacl -O atime=off -O canmount=off -O compression=zstd -O normalization=formD -O xattr=sa -O mountpoint=none -O redundant_metadata=most -R /mnt pool1 mirror nvme-SAMSUNG_MZQL21T9HCJR-00A07_XXXX nvme-SAMSUNG_MZQL21T9HCJR-00A07_XXXX`

zpool reports ashift 12.
```
root@server:~# zpool get ashift
NAME   PROPERTY  VALUE   SOURCE
pool1  ashift    12      local
```

Than created dataset for mysql with smaller recordsize
`zfs create -o mountpoint=/var/lib/mysql -o recordsize=16K pool1/system/root/var/mysql`

After filling the database with data, total size is two times bigger than apparent size, even with zstd compression.

After some debugging, I found using
`zdb -C pool1`
that zfs silently increased ashift from 12 to 15.
```
        vdev_tree:
            type: 'root'
            id: 0
            guid: 11760869303735270092
            create_txg: 4
            children[0]:
                type: 'mirror'
                id: 0
                guid: 14241289099192218134
                metaslab_array: 132
                metaslab_shift: 34
                ashift: 15
                asize: 1918095851520
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 129
```

The reason behind this is that the used nvme disk has larger blocksize than 4kB.
This means zfs will allocate one block from disk with size 2^15 (32kB) to store one 16kB block, practically wasting half of the space.

This is not expected behavior. I think this should be changed:
1, zpool create should print notice when increasing ashift to match disk block size
2, zpool get ashift should report maximum ashift from all top level vdevs
3, (optional) I see no valid reason to create dataset with recordsize smaller than ashift. Maybee zfs create should not create that dataset without "-f" flag to warn administrator.
