### ISSUE TITLE
zvol snapshot inconsistent with source 

### ISSUE THREAD

**Issue by aayushshah15** [openzfs/zfs#15875]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 22.04
Kernel Version	|  5.15.0-89-generic
Architecture	| amd64
OpenZFS Version	| 2.1.5

### Describe the problem you're observing
We're observing that a zvol snapshot is not consistent with its source zvol immediately after the snapshot was taken, without any modifications being made to the source zvol. 

At a high level, we're creating clones of a base zvol (which contains an ext4 formatted ubuntu filesystem) to pass off to [firecracker](https://github.com/firecracker-microvm/firecracker) microVMs. We're seeing that sometimes the microVM detects that its `dpkg` database is in a corrupt state. It seems to point to the `/var/lib/dpkg/info/format` file being empty as the reason for this. 

Manually inspecting the contents of our base zvol (which is unmounted immediately after it is hydrated with our ubuntu rootfs) confirms that the `/var/lib/dpkg/info/format` is _not_ empty, whereas the same file in a clone of the snapshot _is_ empty.  

### Describe how to reproduce the problem

Here is a snippet from an ansible playbook that seems to reliably reproduce the issue
```
    - name: Extract the tar file to the zvol
      ansible.builtin.shell:
          cmd: "tar -xf {{ destination_directory }}/{{ image_name.split(':')[1] }}.tar -C /mnt/rootfs-{{ image_tag }}"

    - name: Assert that the zvol contains "1" in the /var/lib/dpkg/info/format file.
      ansible.builtin.shell:
        cmd: "grep -q 1 /mnt/rootfs-{{ image_tag }}/var/lib/dpkg/info/format"
      register: format_file
      until: format_file.rc == 0

    - name: Create a snapshot of the zvol
      ansible.builtin.shell:
        cmd: "zfs snapshot bspool/rootfs-{{ image_tag }}@latest"

    - name: Clone the snapshot
      ansible.builtin.shell:
        cmd: "zfs clone bspool/rootfs-{{ image_tag }}@latest bspool/rootfs-{{ image_tag }}-latest"

    - name: Mount the cloned zvol
      ansible.builtin.shell:
        cmd: "mount -t ext4 /dev/zvol/bspool/rootfs-{{ image_tag }}-latest /mnt/rootfs-{{ image_tag }}-latest"

    - name: Assert that snapshot contains "1" in the /var/lib/dpkg/info/format file.
      ansible.builtin.shell:
        cmd: "grep -q 1 /mnt/rootfs-{{ image_tag }}-latest/var/lib/dpkg/info/format"
      register: format_file
      until: format_file.rc == 0
```

In this script, the first assertion (second step) succeeds but the second assertion (the last step) doesn't. Are we misunderstanding something here?
