### ISSUE TITLE
Single Spare disk attached in two places (used twice simultaneously)

### ISSUE THREAD

**Issue by hellermf** [openzfs/zfs#16398]
Type | Version/Name
 --- | ---
Distribution Name	|   CentOS Linux
Distribution Version	| release 7.9.2009
Kernel Version	| 3.10.0-1160.71.1.el7.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.0.7-1

### Describe the problem you're observing

We have a server where the ZFS pool somehow got in a state where a spare drive, "slot_15", is in use in two spots at once and I am pretty sure that is not a valid state for a spare. Based on the "zfs history" output this seems to have happened solely from automatic spare management behavior from ZFS and ZED, not any human sysadmin issuing any strange or stupid commands. Unfortunately is a production server so we are going to have to prioritize uptime and preserving the data over troubleshooting and debugging ZFS (and it is an old ZFS version on an old OS and kernel which is also not ideal for troubleshooting & debugging). However I figured it was still worth reporting the problem despite those limits, even if it doesn't help us it may help someone else in the future, I know I searched for someone reporting a similar problem without success. Any insight into what might have happened or how to approach fixing this is greatly appreciated.

```
[root@X ~]# zpool status -s
  pool: pool0
 state: DEGRADED
status: One or more devices are faulted in response to persistent errors.
        Sufficient replicas exist for the pool to continue functioning in a
        degraded state.
action: Replace the faulted device, or use 'zpool clear' to mark the device
        repaired.
  scan: resilvered 20.2T in 14 days 15:38:14 with 0 errors on Tue Jul 16 17:40:27 2024
config:

        NAME                        STATE     READ WRITE CKSUM  SLOW
        pool0                       DEGRADED     0     0     0     -
          raidz2-0                  DEGRADED     0     0     0     -
            slot_0                  ONLINE       0     0     0     0
            slot_1                  ONLINE       0     0     0     0
            slot_2                  ONLINE       0     0     0     0
            slot_3                  ONLINE       0     0     0     0
            slot_4                  ONLINE       0     0     0     0
            slot_5                  ONLINE       0     0     0     0
            spare-6                 DEGRADED     0     0  704M     -
              11085096675090453721  UNAVAIL      0     0     0     0  was /dev/disk/by-vdev/slot_6-part1
              slot_15               ONLINE       0     0     0     0
            spare-7                 DEGRADED     0     0 6.76M     -
              slot_7                FAULTED     14     0     0     0  too many errors
              slot_15               ONLINE       0     0     0     0
            slot_8                  ONLINE       0     0     0     0
            slot_9                  ONLINE       0     0     0     0
            slot_10                 ONLINE       0     0     0     0
            slot_11                 ONLINE       0     0     0     0
            slot_12                 ONLINE       0     0     0     0
            slot_13                 DEGRADED   440     0   174     0  too many errors
            slot_14                 ONLINE       0     0     0     0
        spares
          slot_15                   INUSE     currently in use

errors: No known data errors

[root@x ~]# zpool history
History for 'pool0':
2019-08-16.17:49:51 zpool create -m none pool0 raidz2 slot_0 slot_1 slot_2 slot_3 slot_4 slot_5 slot_6 slot_7 slot_8 slot_9 slot_10 slot_11 slot_12 slot_13 slot_14 spare slot_15
2019-08-16.17:51:39 zfs create -o compression=lz4 -o xattr=sa -o acltype=posixacl -o mountpoint=/data1 pool0/data1
2019-08-19.14:25:23 zpool import -c /etc/zfs/zpool.cache -aN
[... more 'zpool import' lines corresponding to system reboots...]
2023-12-20.10:07:48 zpool import -c /etc/zfs/zpool.cache -aN
2024-05-30.21:43:31 zpool import -c /etc/zfs/zpool.cache -aN
```

### Describe how to reproduce the problem

I do not know how to reproduce this, I have been a sysadmin for many servers with ZFS storage for many years and have never seen or heard of this happening before.

### Include any warning/errors/backtraces from the system logs

I'm not sure there is any corresponding error that I found obviously relevant. If there is something specific I can provide please let me know.

**Comment by rincebrain** [comment]
`zdb -C`'s output may provide more information.

**Comment by hellermf** [comment]
Yes, that is a good thought. Here is the relevant excerpt from the `zdb -C` output. Note that we have since replaced the "slot_6" drive after the `zpool status` output in the original post. 

My untrained eye doesn't see anything surprising in the `zdb -C` output, it is what I would expect given the `zpool status` output however I may be overlooking something, perhaps with the `is_spare: 1` or  `unspare: 1` properties? In the first group the `slot_15` spare has `is_spare: 1` whereas in the second group the duplicate `slot_15` entry does not have `is_spare: 1`. In the second group the faulted disk has `unspare: 1`.

```
[root@x ~]# zdb -C
pool0:
[...]
            children[6]:
                type: 'spare'
                id: 6
                guid: 2551349573857462274
                whole_disk: 0
                create_txg: 4
                children[0]:
                    type: 'replacing'
                    id: 0
                    guid: 17442985336891107132
                    whole_disk: 0
                    create_txg: 4
                    children[0]:
                        type: 'disk'
                        id: 0
                        guid: 11085096675090453721
                        path: '/dev/disk/by-vdev/slot_6-part1/old'
                        phys_path: 'pci-0000:3b:00.0-scsi-0:2:6:0'
                        whole_disk: 1
                        not_present: 1
                        DTL: 277
                        create_txg: 4
                        expansion_time: 1721773740
                        com.delphix:vdev_zap_leaf: 136
                    children[1]:
                        type: 'disk'
                        id: 1
                        guid: 8580536667550062483
                        path: '/dev/disk/by-vdev/slot_6-part1'
                        devid: 'scsi-364cd98f05dc3e8002e0d9ac0adced5c3-part1'
                        phys_path: 'pci-0000:3b:00.0-scsi-0:2:6:0'
                        whole_disk: 1
                        DTL: 2054
                        create_txg: 4
                        com.delphix:vdev_zap_leaf: 2049
                        resilver_txg: 32523349
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 14263400900456517779
                    path: '/dev/disk/by-vdev/slot_15-part1'
                    devid: 'scsi-364cd98f05dc3e80024e96a6817ebfb66-part1'
                    phys_path: 'pci-0000:3b:00.0-scsi-0:2:17:0'
                    whole_disk: 1
                    is_spare: 1
                    DTL: 8
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 158
            children[7]:
                type: 'spare'
                id: 7
                guid: 5778773763825101959
                whole_disk: 0
                create_txg: 4
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 7144179735447276755
                    path: '/dev/disk/by-vdev/slot_7-part1'
                    devid: 'scsi-364cd98f05dc3e80024e96a6717008247-part1'
                    phys_path: 'pci-0000:3b:00.0-scsi-0:2:7:0'
                    whole_disk: 1
                    DTL: 278
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 137
                    faulted: 1
                    unspare: 1
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 14263400900456517779
                    path: '/dev/disk/by-vdev/slot_15-part1'
                    devid: 'scsi-364cd98f05dc3e80024e96a6817ebfb66-part1'
                    phys_path: 'pci-0000:3b:00.0-scsi-0:2:17:0'
                    whole_disk: 1
                    DTL: 515
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 514
 [...]
```
