### ISSUE TITLE
zpool import fails to properly show available pools with same name

### ISSUE THREAD

**Issue by eharris** [openzfs/zfs#16989]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 12 (bookworm)
Kernel Version	| 6.1.0-30-amd64
Architecture	| amd64
OpenZFS Version	| zfs-2.2.7-1~bpo12+1

### Describe the problem you're observing

`zpool import` fails to properly show available pools with same name

### Describe how to reproduce the problem

```
# truncate -s 10G zdev1
# truncate -s 10G zdev2
# truncate -s 10G zdev3
# zpool create test mirror /raid/temp/zdev1 /raid/temp/zdev2 /raid/temp/zdev3
# zpool offline test /raid/temp/zdev2
# zpool detach test /raid/temp/zdev2
# zdb -l zdev1 |grep pool_guid
    pool_guid: 9117558645899222510
# zpool reguid test
# zdb -l zdev1 |grep pool_guid
    pool_guid: 16189010088442266690
# zpool export test
# zpool import -d /raid/temp
   pool: test
     id: 16189010088442266690
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        test                  ONLINE
          mirror-0            ONLINE
            /raid/temp/zdev1  ONLINE
            /raid/temp/zdev3  ONLINE

   pool: test
     id: 16189010088442266690
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        test                  ONLINE
          mirror-0            ONLINE
            /raid/temp/zdev1  ONLINE
            /raid/temp/zdev3  ONLINE
# zdb -l zdev2 |grep pool_guid
    pool_guid: 9117558645899222510
```
As you can see, the `test` pool was listed twice with the same info, even though the copy from zdev2 should have a different guid and members.

```
# mv zdev1 zdev3 ..
# zpool import -d /raid/temp
   pool: test
     id: 9117558645899222510
  state: DEGRADED
status: One or more devices are missing from the system.
 action: The pool can be imported despite missing or damaged devices.  The
        fault tolerance of the pool may be compromised if imported.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-2Q
 config:

        test                  DEGRADED
          mirror-0            DEGRADED
            /raid/temp/zdev1  UNAVAIL  cannot open
            /raid/temp/zdev2  ONLINE
            /raid/temp/zdev3  UNAVAIL  cannot open
# mv ../zdev[13] .
# zpool import -d /raid/temp
   pool: test2
     id: 16189010088442266690
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        test2                 ONLINE
          mirror-0            ONLINE
            /raid/temp/zdev1  ONLINE
            /raid/temp/zdev3  ONLINE

   pool: test
     id: 16189010088442266690
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        test                  ONLINE
          mirror-0            ONLINE
            /raid/temp/zdev1  ONLINE
            /raid/temp/zdev3  ONLINE
```

### Include any warning/errors/backtraces from the system logs

none
