### ISSUE TITLE
High CPU usage of zfs_iput_taskq and slow writes

### ISSUE THREAD

**Issue by satmandu** [openzfs/zfs#1953]
I have a folder shared via netatalk to do time machine backups.  I'm attempting to backup ~ 250Gb of data (replacing another 250gb of data). The backup slows to a crawl about ~30Gb in though. Top reveals that zfs_iput_taskq is at 99%. Writes to other zpools on other disks also slow to a near crawl at this point.

On an Ubuntu 13.10 system with a 3.12.3 kernel. (This is an issue I have seen before.  I've usually been able to reboot once the zfs_iput_tasq is done, and then the issue goes away for a while, but it comes back.)

I've also now set xattr=sa since I've read a little bit on how this might be connected... but I assume this doesn't take effect immediately.

top:

```
top - 11:16:12 up 1 day, 21:20,  1 user,  load average: 1.12, 1.38, 3.39
Tasks: 424 total,   3 running, 419 sleeping,   0 stopped,   2 zombie
%Cpu(s):  0.2 us, 50.4 sy,  0.0 ni, 48.6 id,  0.8 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   6095000 total,  5734220 used,   360780 free,       44 buffers
KiB Swap:   975868 total,    31744 used,   944124 free,  1818300 cached

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND           
 1665 root       0 -20     0    0    0 R  99.9  0.0 917:04.91 zfs_iput_taskq/   
 5761 satmandu   20   0 20768 1784 1116 R   0.7  0.0   0:00.07 top               

```

zpool iostat 1:

```
backups      529G  3.12T      3      0  20.5K      0
----------  -----  -----  -----  -----  -----  -----
backups      529G  3.12T      6      0  33.5K      0
----------  -----  -----  -----  -----  -----  -----
backups      529G  3.12T      3      0  18.5K      0
----------  -----  -----  -----  -----  -----  -----
backups      529G  3.12T      5      0  19.0K      0
----------  -----  -----  -----  -----  -----  -----
```

zdb output:

```
backups:
    version: 28
    name: 'backups'
    state: 0
    txg: 3804191
    pool_guid: 7826503835675459938
    hostname: 'backup'
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 7826503835675459938
        children[0]:
            type: 'disk'
            id: 0
            guid: 15722699178899966303
            path: '/dev/disk/by-id/ata-Hitachi_HDS722020ALA330_JK1130YAGSJLYT-part2'
            whole_disk: 0
            metaslab_array: 31
            metaslab_shift: 31
            ashift: 12
            asize: 2000050192384
            is_log: 0
            DTL: 41
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 9435143644745875
            path: '/dev/disk/by-id/ata-Hitachi_HDS722020ALA330_JK1130YAGSM8ZT-part2'
            whole_disk: 0
            metaslab_array: 444
            metaslab_shift: 31
            ashift: 9
            asize: 2000050192384
            is_log: 0
            DTL: 42
            create_txg: 20734
    features_for_read:
```

module info:

zfs

```
/sbin/modinfo zfs
filename:       /lib/modules/3.12.3-031203-generic/updates/dkms/zfs.ko
license:        CDDL
author:         Sun Microsystems/Oracle, Lawrence Livermore National Laboratory
description:    ZFS
srcversion:     52118DBD850807AF7765395
depends:        spl,znvpair,zcommon,zunicode,zavl
vermagic:       3.12.3-031203-generic SMP mod_unload modversions 
parm:           zvol_inhibit_dev:Do not create zvol device nodes (uint)
parm:           zvol_major:Major number for zvol device (uint)
parm:           zvol_threads:Number of threads for zvol device (uint)
parm:           zvol_max_discard_blocks:Max number of blocks to discard at once (ulong)
parm:           zio_injection_enabled:Enable fault injection (int)
parm:           zio_bulk_flags:Additional flags to pass to bulk buffers (int)
parm:           zio_delay_max:Max zio millisec delay before posting event (int)
parm:           zio_requeue_io_start_cut_in_line:Prioritize requeued I/O (int)
parm:           zfs_sync_pass_deferred_free:defer frees starting in this pass (int)
parm:           zfs_sync_pass_dont_compress:don't compress starting in this pass (int)
parm:           zfs_sync_pass_rewrite:rewrite new bps starting in this pass (int)
parm:           zil_replay_disable:Disable intent logging replay (int)
parm:           zfs_nocacheflush:Disable cache flushes (int)
parm:           zil_slog_limit:Max commit bytes to separate log device (ulong)
parm:           zfs_read_chunk_size:Bytes to read per chunk (long)
parm:           zfs_immediate_write_sz:Largest data block to write to zil (long)
parm:           zfs_flags:Set additional debugging flags (int)
parm:           zfs_recover:Set to attempt to recover from fatal errors (int)
parm:           zfs_expire_snapshot:Seconds to expire .zfs/snapshot (int)
parm:           zfs_vdev_max_pending:Max pending per-vdev I/Os (int)
parm:           zfs_vdev_min_pending:Min pending per-vdev I/Os (int)
parm:           zfs_vdev_aggregation_limit:Max vdev I/O aggregation size (int)
parm:           zfs_vdev_time_shift:Deadline time shift for vdev I/O (int)
parm:           zfs_vdev_ramp_rate:Exponential I/O issue ramp-up rate (int)
parm:           zfs_vdev_read_gap_limit:Aggregate read I/O over gap (int)
parm:           zfs_vdev_write_gap_limit:Aggregate write I/O over gap (int)
parm:           zfs_vdev_mirror_switch_us:Switch mirrors every N usecs (int)
parm:           zfs_vdev_scheduler:I/O scheduler (charp)
parm:           zfs_vdev_cache_max:Inflate reads small than max (int)
parm:           zfs_vdev_cache_size:Total size of the per-disk cache (int)
parm:           zfs_vdev_cache_bshift:Shift size to inflate reads too (int)
parm:           zfs_txg_timeout:Max seconds worth of delta per txg (int)
parm:           zfs_read_history:Historic statistics for the last N reads (int)
parm:           zfs_read_history_hits:Include cache hits in read history (int)
parm:           zfs_txg_history:Historic statistics for the last N txgs (int)
parm:           zfs_deadman_synctime:Expire in units of zfs_txg_synctime_ms (ulong)
parm:           zfs_deadman_enabled:Enable deadman timer (int)
parm:           spa_config_path:SPA config file (/etc/zfs/zpool.cache) (charp)
parm:           zfs_autoimport_disable:Disable pool import at module load (int)
parm:           metaslab_debug:keep space maps in core to verify frees (int)
parm:           zfs_zevent_len_max:Max event queue length (int)
parm:           zfs_zevent_cols:Max event column width (int)
parm:           zfs_zevent_console:Log events to the console (int)
parm:           zfs_top_maxinflight:Max I/Os per top-level (int)
parm:           zfs_resilver_delay:Number of ticks to delay resilver (int)
parm:           zfs_scrub_delay:Number of ticks to delay scrub (int)
parm:           zfs_scan_idle:Idle window in clock ticks (int)
parm:           zfs_scan_min_time_ms:Min millisecs to scrub per txg (int)
parm:           zfs_free_min_time_ms:Min millisecs to free per txg (int)
parm:           zfs_resilver_min_time_ms:Min millisecs to resilver per txg (int)
parm:           zfs_no_scrub_io:Set to disable scrub I/O (int)
parm:           zfs_no_scrub_prefetch:Set to disable scrub prefetching (int)
parm:           zfs_no_write_throttle:Disable write throttling (int)
parm:           zfs_write_limit_shift:log2(fraction of memory) per txg (int)
parm:           zfs_txg_synctime_ms:Target milliseconds between txg sync (int)
parm:           zfs_write_limit_min:Min txg write limit (ulong)
parm:           zfs_write_limit_max:Max txg write limit (ulong)
parm:           zfs_write_limit_inflated:Inflated txg write limit (ulong)
parm:           zfs_write_limit_override:Override txg write limit (ulong)
parm:           zfs_prefetch_disable:Disable all ZFS prefetching (int)
parm:           zfetch_max_streams:Max number of streams per zfetch (uint)
parm:           zfetch_min_sec_reap:Min time before stream reclaim (uint)
parm:           zfetch_block_cap:Max number of blocks to fetch at a time (uint)
parm:           zfetch_array_rd_sz:Number of bytes in a array_read (ulong)
parm:           zfs_pd_blks_max:Max number of blocks to prefetch (int)
parm:           zfs_mdcomp_disable:Disable meta data compression (int)
parm:           zfs_nopwrite_enabled:Enable NOP writes (int)
parm:           zfs_dedup_prefetch:Enable prefetching dedup-ed blks (int)
parm:           zfs_dbuf_state_index:Calculate arc header index (int)
parm:           zfs_arc_min:Min arc size (ulong)
parm:           zfs_arc_max:Max arc size (ulong)
parm:           zfs_arc_meta_limit:Meta limit for arc size (ulong)
parm:           zfs_arc_meta_prune:Bytes of meta data to prune (int)
parm:           zfs_arc_grow_retry:Seconds before growing arc size (int)
parm:           zfs_arc_shrink_shift:log2(fraction of arc to reclaim) (int)
parm:           zfs_arc_p_min_shift:arc_c shift to calc min/max arc_p (int)
parm:           zfs_disable_dup_eviction:disable duplicate buffer eviction (int)
parm:           zfs_arc_memory_throttle_disable:disable memory throttle (int)
parm:           zfs_arc_min_prefetch_lifespan:Min life of prefetch block (int)
parm:           l2arc_write_max:Max write bytes per interval (ulong)
parm:           l2arc_write_boost:Extra write bytes during device warmup (ulong)
parm:           l2arc_headroom:Number of max device writes to precache (ulong)
parm:           l2arc_headroom_boost:Compressed l2arc_headroom multiplier (ulong)
parm:           l2arc_feed_secs:Seconds between L2ARC writing (ulong)
parm:           l2arc_feed_min_ms:Min feed interval in milliseconds (ulong)
parm:           l2arc_noprefetch:Skip caching prefetched buffers (int)
parm:           l2arc_nocompress:Skip compressing L2ARC buffers (int)
parm:           l2arc_feed_again:Turbo L2ARC warmup (int)
parm:           l2arc_norw:No reads during writes (int)
```

spl:

```
/sbin/modinfo spl
filename:       /lib/modules/3.12.3-031203-generic/updates/dkms/spl.ko
license:        GPL
description:    Solaris Porting Layer
author:         Lawrence Livermore National Labs
srcversion:     E5FEF2127809879D7CF69EA
depends:        
vermagic:       3.12.3-031203-generic SMP mod_unload modversions 
parm:           spl_hostid:The system hostid. (ulong)
parm:           spl_hostid_path:The system hostid file (/etc/hostid) (charp)
parm:           spl_kmem_cache_expire:By age (0x1) or low memory (0x2) (uint)
parm:           spl_debug_subsys:Subsystem debugging level mask. (ulong)
parm:           spl_debug_mask:Debugging level mask. (ulong)
parm:           spl_debug_printk:Console printk level mask. (ulong)
parm:           spl_debug_mb:Total debug buffer size. (int)
parm:           spl_debug_panic_on_bug:Panic on BUG (uint)
```
