### ISSUE TITLE
Importing a pool with corrupted log device

### ISSUE THREAD

**Issue by RyanHow** [openzfs/zfs#2099]
If a log device is corrupted, zpool import will refuse to import the pool. The workaround is to remove the actual device from the system, then zpool import -m to import the pool with the missing device.

It would be great to be able to zpool import -f (Or some other flag like -m) and import the pool regardless of the corrupt log device. The pool could then just import in a degraded state (like when a device is missing).

It just appears to be a hole in the zpool import command. Although data corruption in the log device could result in lost data, the only thing that you can really do in this case is import the pool regardless and continue on with the lost data.

**Comment by durval-menezes** [comment]
Hello, 

Referring to the following, above: https://github.com/zfsonlinux/zfs/issues/2099#issuecomment-54532363, more specifically to that part: 

> Giving either as 'zpool remove git xxx' gives no error but doesn't change the pool." 

I'm having the exact same issue with one of my pools here, running ZoL's latest stable (0.6.5.3) installed from the official repo on EL6. The only difference is that, contrary to @dswartz, I tried to export the pool, remove the log device and then import it back in, but *still* the "zpool remove" accomplishes nothing and the device keeps showing on zpool status. I've posted extensively about the problem on a zfs-discuss mailing list thread starting here: http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-December/024006.html

I'm going ahead and opening a new issue for this, referring to this one, and to the above mail thread.

Cheers,
Durval.

**Comment by ksalman** [comment]
I am also running into this - cannot remove an OFFLINE zil device. I am using version 0.6.5.6-0ubuntu14.


	NAME                                    STATE     READ WRITE CKSUM
	tank                                    DEGRADED     0     0     0
	  mirror-0                              ONLINE       0     0     0
	    sda                                 ONLINE       0     0     0
	    sdb                                 ONLINE       0     0     0
	  mirror-1                              ONLINE       0     0     0
	    sdc                                 ONLINE       0     0     0  (resilvering)
	    sdd                                 ONLINE       0     0     0
	logs
	  64712f3c-9b0a-11e6-a777-001b21709ddc  OFFLINE      0     0     0

**Comment by zeigerpuppy** [comment]
I am having a (real-life) problem importing a pool at the moment.
My log device corrupted due to a power outage and the pool will now not import even with the `missing` option.
Is there a way to force it to import, I've tried all the commands I can think of:

The closest I get is with:

```
zpool import -f -m -d /dev/disk/by-id/scsi-35000cca03e167XXX-part1
```
which returns

```
   pool: data
     id: 13736941278548912923
  state: UNAVAIL
 status: One or more devices are missing from the system.
 action: The pool cannot be imported. Attach the missing
	devices and try again.
   see: http://zfsonlinux.org/msg/ZFS-8000-6X
 config:

	data                                        UNAVAIL  missing device
	  raidz2-0                                  ONLINE
	    scsi-35000cca03e94cXXX                 ONLINE
	    scsi-35000cca03ea73XXX                  ONLINE
	    scsi-35000cca03eb11XXX                  ONLINE
	    scsi-35000cca03eb42XXX                 ONLINE
	    scsi-35000cca03e088XXX                  ONLINE
	    scsi-35000cca01adb1XXX                  ONLINE
	    scsi-35000cca03e167XXX                  ONLINE
	    scsi-35000cca03e172XXX                  ONLINE
	logs
	  ata-MK0200GCTYV_BTTV320101VFXXX-part6  UNAVAIL  corrupted data

	Additional devices are known to be part of this pool, though their
	exact configuration cannot be determined.
```

I also tried reformatting the log partition but that doesn't seem to help.
I guess there must be some way to offline the log, but can't seem to find a way to do it in a pool that won't import.

**Comment by behlendorf** [comment]
@zeigerpuppy you're absolutely on the right track, the `-m` option should have worked.  Can you try importing your pool again with the following command:

```
zpool import -f -m -d /dev/disk/by-id/ tank
```

Assuming that fails, please grab the kernel debug log by dumping `/proc/spl/kstat/zfs/dbgmsg`.  The lines of interest will be prefixed with `spa_load` so I'd recommend running something like:

```
grep spa_load /proc/spl/kstat/zfs/dbgmsg
```

This should give us a better indication of exactly what the issue is.

**Comment by zeigerpuppy** [comment]
Thanks for the tip.
As you predicted the pool fails to import, the messages from `/proc/spl/kstat/zfs/dbgmsg` are below:

```
1578663794   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633752
1578663794   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578663794   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633752
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): some log devices are missing, ZIL is dropped.
1578663795   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: vdev_load failed [error=2]
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633751
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633751
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): some log devices are missing, ZIL is dropped.
1578663795   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: vdev_load failed [error=2]
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633750
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633750
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): some log devices are missing, ZIL is dropped.
1578663795   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: vdev_load failed [error=2]
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664082   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664082   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664082   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664082   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578664137   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664137   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664137   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664137   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578664246   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664247   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664247   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633753
1578664247   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633752
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633752
1578664247   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633751
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633751
1578664248   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633750
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633750
1578664248   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664260   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664260   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664260   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664260   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578697883   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578697883   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578697883   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578697883   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
```

I have also included the output of zdb (sanitised serial numbers) for reference:

```
data:
    version: 5000
    name: 'data'
    state: 0
    txg: 33623486
    pool_guid: 13736941278548912923
    errata: 0
    hostid: 8323329
    hostname: 'ocelot'
    com.delphix:has_per_vdev_zaps
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 13736941278548912923
        children[0]:
            type: 'raidz'
            id: 0
            guid: 10302097311291941285
            nparity: 2
            metaslab_array: 34
            metaslab_shift: 37
            ashift: 12
            asize: 24004626743296
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 475
            children[0]:
                type: 'disk'
                id: 0
                guid: 6395614434348585949
                path: '/dev/disk/by-id/scsi-35000cca03e94cXXX-part1'
                whole_disk: 1
                DTL: 474
                create_txg: 4
                com.delphix:vdev_zap_leaf: 477
            children[1]:
                type: 'disk'
                id: 1
                guid: 13886622606314949005
                path: '/dev/disk/by-id/scsi-35000cca03ea73XXX-part1'
                whole_disk: 1
                DTL: 473
                create_txg: 4
                com.delphix:vdev_zap_leaf: 478
            children[2]:
                type: 'disk'
                id: 2
                guid: 15223255819206260964
                path: '/dev/disk/by-id/scsi-35000cca03eb11XXX-part1'
                whole_disk: 1
                DTL: 472
                create_txg: 4
                com.delphix:vdev_zap_leaf: 479
            children[3]:
                type: 'disk'
                id: 3
                guid: 13152668632038442322
                path: '/dev/disk/by-id/scsi-35000cca03eb42XXX-part1'
                whole_disk: 1
                DTL: 471
                create_txg: 4
                com.delphix:vdev_zap_leaf: 480
            children[4]:
                type: 'disk'
                id: 4
                guid: 10359585613055231207
                path: '/dev/disk/by-id/scsi-35000cca03e088XXX-part1'
                devid: 'scsi-35000cca03e088XXX-part1'
                phys_path: 'pci-0000:03:00.0-sas-phy5-lun-0'
                whole_disk: 1
                DTL: 488
                create_txg: 4
                com.delphix:vdev_zap_leaf: 487
            children[5]:
                type: 'disk'
                id: 5
                guid: 12665232198200720196
                path: '/dev/disk/by-id/scsi-35000cca01adb1XXX-part1'
                devid: 'scsi-35000cca01adb1XXX-part1'
                phys_path: 'pci-0000:03:00.0-sas-phy6-lun-0'
                whole_disk: 1
                DTL: 641
                create_txg: 4
                com.delphix:vdev_zap_leaf: 640
            children[6]:
                type: 'disk'
                id: 6
                guid: 10521707952703103872
                path: '/dev/disk/by-id/scsi-35000cca03e167XXX-part1'
                whole_disk: 1
                DTL: 69
                create_txg: 4
                com.delphix:vdev_zap_leaf: 483
            children[7]:
                type: 'disk'
                id: 7
                guid: 6315495063040771963
                path: '/dev/disk/by-id/scsi-35000cca03e172XXX-part1'
                devid: 'scsi-35000cca03e172XXX-part1'
                phys_path: 'pci-0000:03:00.0-sas-phy4-lun-0'
                whole_disk: 1
                DTL: 514
                create_txg: 4
                com.delphix:vdev_zap_leaf: 494
        children[1]:
            type: 'disk'
            id: 1
            guid: 8899809195679796448
            path: '/dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF20XXXX-part6'
            whole_disk: 0
            metaslab_array: 38
            metaslab_shift: 25
            ashift: 9
            asize: 5995233280
            is_log: 1
            DTL: 468
            create_txg: 27392809
            com.delphix:vdev_zap_leaf: 485
            com.delphix:vdev_zap_top: 486
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

The pool recently had two drives replaced and resilvered, which all went well.
