### ISSUE TITLE
PANIC: blkptr at ffff88018b77e848 DVA 0 has invalid OFFSET 906461288960

### ISSUE THREAD

**Issue by JuliaVixen** [openzfs/zfs#5034]
This seems to be slightly different from #4582, in that this is now an invalid OFFSET, rather than invalid VDEV... But anyway, All you need to do to reproduce this, is find some drives from an old zpool, which have been sitting in a box in your garage for a few years, plug them in, and then run `zpool import`, and this happens:

```
[370017.756762] PANIC: blkptr at ffff88018b77e848 DVA 0 has invalid OFFSET 906461288960
[370017.756861] Showing stack for process 25604
[370017.756863] CPU: 3 PID: 25604 Comm: zpool Tainted: P        W  O    4.4.6-gentoo-debug2 #1
[370017.756863] Hardware name: Supermicro X10SLL-F/X10SLL-SF/X10SLL-F/X10SLL-SF, BIOS 1.0a 06/11/2013
[370017.756864]  0000000000000000 ffff88025395b848 ffffffff8130fa9d 0000000000000003
[370017.756866]  0000000000000000 ffff88025395b858 ffffffffa0a545ac ffff88025395b988
[370017.756867]  ffffffffa0a54644 0000000000000400 00066860c7d08680 61207274706b6c62
[370017.756869] Call Trace:
[370017.756873]  [<ffffffff8130fa9d>] dump_stack+0x4d/0x63
[370017.756878]  [<ffffffffa0a545ac>] spl_dumpstack+0x3d/0x3f [spl]
[370017.756881]  [<ffffffffa0a54644>] vcmn_err+0x96/0xd3 [spl]
[370017.756884]  [<ffffffff810e9df7>] ? kmem_cache_alloc+0x69/0xae
[370017.756887]  [<ffffffffa0a50184>] ? spl_kmem_cache_alloc+0x10c/0xa9f [spl]
[370017.756908]  [<ffffffffa14fab78>] zfs_panic_recover+0x4d/0x4f [zfs]
[370017.756917]  [<ffffffffa148c0be>] ? arc_write_done+0x535/0x535 [zfs]
[370017.756929]  [<ffffffffa154ffd0>] zfs_blkptr_verify+0x218/0x271 [zfs]
[370017.756932]  [<ffffffff814d0a10>] ? mutex_unlock+0x9/0xb
[370017.756944]  [<ffffffffa155005d>] zio_read+0x34/0xd1 [zfs]
[370017.756952]  [<ffffffffa148c0be>] ? arc_write_done+0x535/0x535 [zfs]
[370017.756960]  [<ffffffffa148f593>] arc_read+0xbff/0xc9a [zfs]
[370017.756972]  [<ffffffffa14a9614>] dmu_objset_open_impl+0x1a6/0x83c [zfs]
[370017.756974]  [<ffffffff81068557>] ? add_wait_queue+0x44/0x44
[370017.756988]  [<ffffffffa14cffd8>] dsl_pool_init+0x31/0x56 [zfs]
[370017.757004]  [<ffffffffa14f0b77>] spa_load+0x988/0x1c80 [zfs]
[370017.757019]  [<ffffffffa14f2ff7>] spa_tryimport+0xc3/0x3cd [zfs]
[370017.757031]  [<ffffffffa152b7f6>] zfs_ioc_pool_tryimport+0x38/0x70 [zfs]
[370017.757044]  [<ffffffffa1530b10>] zfsdev_ioctl+0x40e/0x521 [zfs]
[370017.757046]  [<ffffffff810fc891>] do_vfs_ioctl+0x3f5/0x43d
[370017.757048]  [<ffffffff810368d2>] ? __do_page_fault+0x24e/0x367
[370017.757049]  [<ffffffff810fc912>] SyS_ioctl+0x39/0x61
[370017.757050]  [<ffffffff814d2317>] entry_SYSCALL_64_fastpath+0x12/0x6a
```

So, I actually have a piece of paper, with some handwritten notes about this particular zpool configuration. (I must have had the forethought to write this down...) It's four physical disks total, with pairs setup as mirrors.
Mirror 1:
C0T1D0  Hitachi Serial Number JK1131YAHL3WDV
C3T1D0  Hitachi Serial Number JK1131YAHL3KMV
Mirror 2:
C4T1D0  Seagate Serial Number 6VMBT9X6
C2T0D0  Seagate Serial Number 6VMBV9KE

So, one of these drives, JK1131YAHL3KMV (C3T1D0), no longer initializes when plugged in. The motor doesn't spin, and there's nothing on the SATA bus, as though it wasn't even plugged in. I plugged in the other three drives, copied the devices into a temp directory, and ran `zpool import -d tmptmptmp`, and this kernel panic happened, and all zpool commands everywhere are now blocking forever. Also all `zfs` commands, like `zfs list` are now blocking forever too.

Yeah, the disks are different versions, and one has Linux device names, and I replaced a disk or something, so there's probably a different set of disks that go together with this pool... but I really don't expect my OS to crash, if I'm just taking a look at the pool, and not even importing it.

```
localhost ~ # zdb -l tmptmptmp/sdn 
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 13
    name: 'photos'
    state: 0
    txg: 803279
    pool_guid: 14249607062869835550
    hostid: 289600
    hostname: 'vulpis'
    top_guid: 12878039738092356071
    guid: 9243080729443220032
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 1
        guid: 12878039738092356071
        metaslab_array: 29
        metaslab_shift: 32
        ashift: 9
        asize: 500103118848
        is_log: 0
        children[0]:
            type: 'disk'
            id: 0
            guid: 6327015979894131640
            path: '/dev/dsk/c1t1d0p0'
            devid: 'id1,sd@SATA_____ST32000542AS________________6XW1SS9J/q'
            phys_path: '/pci@0,0/pci10de,376@a/pci1095,3132@0/disk@1,0:q'
            whole_disk: 0
            DTL: 222
        children[1]:
            type: 'disk'
            id: 1
            guid: 9243080729443220032
            path: '/dev/dsk/c2t0d0p0'
            devid: 'id1,sd@SATA_____ST3500418AS_________________6VMBV9KE/q'
            phys_path: '/pci@0,0/pci10de,377@f/pci1095,3132@0/disk@0,0:q'
            whole_disk: 0
            DTL: 149
[etc. etc.]

localhost ~ # zdb -l tmptmptmp/sdl 
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 25
    name: 'photos'
    state: 0
    txg: 10393942
    pool_guid: 14249607062869835550
    hostname: 'Gentoo-2012'
    top_guid: 14624263104059772522
    guid: 15027610366694812039
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 14624263104059772522
        metaslab_array: 23
        metaslab_shift: 34
        ashift: 9
        asize: 2000394125312
        is_log: 0
        children[0]:
            type: 'disk'
            id: 0
            guid: 15027610366694812039
            path: '/dev/sde'
            phys_path: '/pci@0,0/pci1043,8239@5/disk@1,0:q'
            whole_disk: 0
            DTL: 28
        children[1]:
            type: 'disk'
            id: 1
            guid: 493362744529803156
            path: '/dev/sdd'
            phys_path: '/pci@0,0/pci1043,8239@5/disk@0,0:c'
            whole_disk: 0
            not_present: 1
            DTL: 18
[etc. etc.]

localhost ~ # zdb -l tmptmptmp/sdp
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 13
    name: 'photos'
    state: 0
    txg: 0
    pool_guid: 14249607062869835550
    hostid: 289600
    hostname: 'vulpis'
    top_guid: 12878039738092356071
    guid: 10993057413123351163
    vdev_children: 2
    vdev_tree:
        type: 'mirror'
        id: 1
        guid: 12878039738092356071
        metaslab_array: 29
        metaslab_shift: 32
        ashift: 9
        asize: 500103118848
        is_log: 0
        children[0]:
            type: 'replacing'
            id: 0
            guid: 16998142661779889098
            whole_disk: 0
            children[0]:
                type: 'disk'
                id: 0
                guid: 10993057413123351163
                path: '/dev/dsk/c4t1d0p0'
                devid: 'id1,sd@AST3500418AS=____________6VMBT9X6/q'
                phys_path: '/pci@0,0/pci1043,8239@5,2/disk@1,0:q'
                whole_disk: 0
                DTL: 150
            children[1]:
                type: 'disk'
                id: 1
                guid: 6327015979894131640
                path: '/dev/dsk/c1t1d0p0'
                devid: 'id1,sd@SATA_____ST32000542AS________________6XW1SS9J/q'
                phys_path: '/pci@0,0/pci10de,376@a/pci1095,3132@0/disk@1,0:q'
                whole_disk: 0
                DTL: 222
        children[1]:
            type: 'disk'
            id: 1
            guid: 9243080729443220032
            path: '/dev/dsk/c2t0d0p0'
            devid: 'id1,sd@SATA_____ST3500418AS_________________6VMBV9KE/q'
            phys_path: '/pci@0,0/pci10de,377@f/pci1095,3132@0/disk@0,0:q'
            whole_disk: 0
            DTL: 149
    create_txg: 0
[etc. etc.]
```

```
localhost ~ # hdparm -I  tmptmptmp/sdp | head

tmptmptmp/sdp:

ATA device, with non-removable media
    Model Number:       ST3500418AS                             
    Serial Number:      6VMBT9X6
    Firmware Revision:  CC38    
    Transport:          Serial

localhost ~ # hdparm -I  tmptmptmp/sdl | head

tmptmptmp/sdl:

ATA device, with non-removable media
    Model Number:       Hitachi HDS722020ALA330                 
    Serial Number:      JK1131YAHL3WDV
    Firmware Revision:  JKAOA28A
    Transport:          Serial, ATA8-AST, SATA 1.0a, SATA II Extensions, SATA Rev 2.5, SATA Rev 2.6; Revision: ATA8-AST T13 Project D1697 Revision 0b

localhost ~ # hdparm -I tmptmptmp/sdn | head

tmptmptmp/sdn:

ATA device, with non-removable media
    Model Number:       ST3500418AS                             
    Serial Number:      6VMBV9KE
    Firmware Revision:  CC38    
    Transport:          Serial
```
