### ISSUE TITLE
PANIC: blkptr at ffff880858559848 DVA 0 has invalid VDEV 1

### ISSUE THREAD

**Issue by frizop** [openzfs/zfs#6671]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    |  7
Linux Kernel                 | 3.10.0-514.26.2.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | spl-0.7.1-1

### Describe the problem you're observing

After adding in a mirror to my root pool, my system failed to boot

### Describe how to reproduce the problem

Starting with the following design:

```config:

        NAME                                        STATE     READ WRITE CKSUM
        rpool                                       ONLINE       0     0     0
          mirror-0                                  ONLINE       0     0     0
            ata-ST8000VN0022-2EL112_ZA17YWA4-part2  ONLINE       0     0     0
            ata-ST8000VN0022-2EL112_ZA17LLRT-part2  ONLINE       0     0     0
```

Then add a new mirror'd pool, mine looks like the following:

```
config:

        NAME                                        STATE     READ WRITE CKSUM
        rpool                                       ONLINE       0     0     0
          mirror-0                                  ONLINE       0     0     0
            ata-ST8000VN0022-2EL112_ZA17YWA4-part2  ONLINE       0     0     0
            ata-ST8000VN0022-2EL112_ZA17LLRT-part2  ONLINE       0     0     0
          mirror-1                                  ONLINE       0     0     0
            ata-ST8000VN0022-2EL112_ZA17SKCL-part2  ONLINE       0     0     0
            ata-ST8000VN0022-2EL112_ZA17Z73E-part2  ONLINE       0     0     0
```

From there, I believe the only thing done was to just reboot. 

I'll explain the history of my design; I started with a single disk, expanded it to a mirror, then added in another mirror. I had rebooted and everything seemed fine after the first mirror expansion, that was a few weeks ago. 

### Include any warning/errors/backtraces from the system logs

![image](https://user-images.githubusercontent.com/3605906/30768489-93ec05d8-9fcd-11e7-9b66-5a288d319ffa.png)
![image](https://user-images.githubusercontent.com/3605906/30768491-9aa02bd4-9fcd-11e7-8cd9-11901d5c382e.png)

Booting the http://list.zfsonlinux.org/zfs-iso/ resulted a clean import, no issues
![image](https://user-images.githubusercontent.com/3605906/30768498-b79e1dc2-9fcd-11e7-9052-a0bc427d4cb2.png)

The issue only seemed to be present after grub loaded the kernel and it failed to fully initialize. 

PMT on #freenode advised me to take a copy of the initramfs I was using, and then the new one (that eventually worked). So I can provide those as well.

As far as what was mentioned, I expect the problem was that the zpool cache was never updated and adding in another mirror-1 to rpool caused it to not know it needed those disks to completely build my `rpool`. 

As far as what I did to solve my issue, I booted into the system rescue iso (from above) and followed these instructions:

```
zpool import rpool
ln -s /dev/disk/by-id/* . -i
for dir in proc sys dev;do mount --bind /$dir /rpool/ROOT/$dir;done
chroot /rpool/ROOT /bin/bash
grub2-mkconfig -o /boot/grub2/grub.cfg
mv /etc/zfs/zpool.cache /
dracut -f -v /boot/initramfs-3.10.0-514.26.2.el7.x86_64.img 3.10.0-514.26.2.el7.x86_64
grub-install --boot-directory=/boot /dev/sda
```

Previously I had tried to just do a "dracut" without either the mkconfig/install and it resulted in some timeouts when trying to boot (not zfs related) so I followed the complete instructions and that seemed to do the trick.

I also kept a copy of the /etc/zfs/zpool.cache 

What should the expected behavior be when using a root pool, moving from a mirror to a two mirror setup be?

Edit: Pulling the zpool.cache out of my initramfs, we found an issue -
```
rpool:
    version: 5000
    name: 'rpool'
    state: 0
    txg: 5780
    pool_guid: 4010814619963324040
    errata: 0
    hostname: 'removed.local'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 4010814619963324040
        children[0]:
            type: 'disk'
            id: 0
            guid: 1552324377184475286
            path: '/dev/disk/by-id/ata-ST8000VN0022-2EL112_ZA17YWA4-part2'
            whole_disk: 0
            metaslab_array: 256
            metaslab_shift: 27
            ashift: 12
            asize: 8001556316160
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 129
            com.delphix:vdev_zap_top: 130
    features_for_read:
```

So this basically points to a single disk, not the other 3 disks I have available in that pool.
