### ISSUE TITLE
Cannot re-online a device.

### ISSUE THREAD

**Issue by danielewood** [openzfs/zfs#7506]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS Linux release 
Distribution Version    | 7.4.1708 (Core)
Linux Kernel                 | 3.10.0-693.21.1.el7
Architecture                 | x86_64
ZFS Version                  | 0.7.8-1
SPL Version                  | 0.7.8-1

### Describe the problem you're observing
Exact same issue as #2013. It appears there is some pool compatibility issue between FreeBSD created pools and ZoL. You cannot offline and re-online a disk from a FreeBSD created pool.

#### Temporary workaround is to `zpool offline -t` the already offline disk, then export/import the pool.

This is a disaster recovery set, so I'll be going ahead and rebuilding it next week as a fresh ZoL array and resyncing the 24TB of data.

I can do further testing on other test servers and recreate the same scenario if needed, just let me know what logs I should be collecting when I do so.

### Describe how to reproduce the problem
-Create zpool under FreeNAS 11.1 u4
-Switch OS to CentOS 7
-Install ZoL with kmod
-Import Pool
-Offline a disk
-Attempt to online the same disk.

### Include any warning/errors/backtraces from the system logs

Relevant zpool history:

```
---FreeBSD Creation:
History for 'data':
2018-04-12.01:50:23 zpool create -o cachefile=/data/zfs/zpool.cache -o failmode=continue -o autoexpand=on -O compression=lz4 -O aclmode=passthrough -O aclinherit=passthrough -f -m /data -o altroot=/mnt data raidz2 /dev/gptid/850a427e-3e2e-11e8-98bb-00259091621e /dev/gptid/85aafea2-3e2e-11e8-98bb-00259091621e /dev/gptid/86447962-3e2e-11e8-98bb-00259091621e /dev/gptid/86f3584c-3e2e-11e8-98bb-00259091621e /dev/gptid/8790baa7-3e2e-11e8-98bb-00259091621e /dev/gptid/8828c6d8-3e2e-11e8-98bb-00259091621e /dev/gptid/88c15f43-3e2e-11e8-98bb-00259091621e /dev/gptid/895ed86e-3e2e-11e8-98bb-00259091621e
2018-04-12.01:50:23 zfs inherit mountpoint data
2018-04-12.01:50:23 zpool set cachefile=/data/zfs/zpool.cache data
2018-04-12.01:50:28 zfs set dedup=off data

---ZoL:
2018-05-04.15:13:28 zpool import data -d /dev/disk/by-vdev/
---Testing offline/online to trigger zed event
2018-05-04.18:05:12 zpool offline data 371584283667699454
2018-05-04.18:10:17 zpool export data
---Since it was not offline -t, the drive didnt come back
2018-05-04.18:11:42 zpool import data -d /dev/disk/by-id/
--- Read issue #2013, tried re-offlining the drive with offline -t
2018-05-04.18:23:11 zpool offline -t data 371584283667699454
2018-05-04.18:23:26 zpool export data
---Import now brings the drive back online
2018-05-04.18:24:38 zpool import data -d /dev/disk/by-id/
2018-05-04.18:25:09 zpool clear data
---Upgraded pool to see if that would resolve the issues
2018-05-04.18:25:36 zpool upgrade data
2018-05-04.18:27:00 zpool offline -t data 371584283667699454
---Did not, had to export and re-import to bring drive back online
2018-05-04.18:27:48 zpool export data
2018-05-04.18:29:58 zpool import data -d /dev/disk/by-vdev/
```

ZDB Output:
```
root@atlasdr:~# zdb -l /dev/disk/by-id/ata-HGST_HDN728080ALE604_VJGBKK0X-part2
------------------------------------
LABEL 0
------------------------------------
    version: 5000
    name: 'data'
    state: 0
    txg: 1417098
    pool_guid: 13742597867845281343
    errata: 0
    hostname: 'atlasdr'
    top_guid: 18090197677160284554
    guid: 568504460133192686
    vdev_children: 1
    vdev_tree:
        type: 'raidz'
        id: 0
        guid: 18090197677160284554
        nparity: 2
        metaslab_array: 45
        metaslab_shift: 39
        ashift: 12
        asize: 63995287437312
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 371584283667699454
            path: '/dev/disk/by-vdev/04-HGST_HDN728080ALE604_VJGD065X-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGD065X-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221100000000-lun-0'
            whole_disk: 1
            DTL: 137
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 13341174030914189782
            path: '/dev/disk/by-vdev/03-HGST_HDN728080ALE604_VJGDMW6X-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGDMW6X-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221101000000-lun-0'
            whole_disk: 1
            DTL: 136
            create_txg: 4
        children[2]:
            type: 'disk'
            id: 2
            guid: 762658606457625342
            path: '/dev/disk/by-vdev/01-HGST_HDN728080ALE604_VJGBWE8X-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGBWE8X-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221102000000-lun-0'
            whole_disk: 1
            DTL: 135
            create_txg: 4
        children[3]:
            type: 'disk'
            id: 3
            guid: 11969135820397406917
            path: '/dev/disk/by-vdev/02-HGST_HDN728080ALE604_VJGBW68X-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGBW68X-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221103000000-lun-0'
            whole_disk: 1
            DTL: 134
            create_txg: 4
        children[4]:
            type: 'disk'
            id: 4
            guid: 568504460133192686
            path: '/dev/disk/by-vdev/08-HGST_HDN728080ALE604_VJGBKK0X-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGBKK0X-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221104000000-lun-0'
            whole_disk: 1
            DTL: 133
            create_txg: 4
        children[5]:
            type: 'disk'
            id: 5
            guid: 9889533431954919638
            path: '/dev/disk/by-vdev/07-HGST_HDN728080ALE604_VJGDR3ZX-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGDR3ZX-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221105000000-lun-0'
            whole_disk: 1
            DTL: 132
            create_txg: 4
        children[6]:
            type: 'disk'
            id: 6
            guid: 10800102329729538606
            path: '/dev/disk/by-vdev/05-HGST_HDN728080ALE604_VJGDPA8X-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGDPA8X-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221107000000-lun-0'
            whole_disk: 1
            DTL: 92
            create_txg: 4
        children[7]:
            type: 'disk'
            id: 7
            guid: 2675042931774243269
            path: '/dev/disk/by-vdev/06-HGST_HDN728080ALE604_VJGDNZSX-part2'
            devid: 'ata-HGST_HDN728080ALE604_VJGDNZSX-part2'
            phys_path: 'pci-0000:03:00.0-sas-0x4433221106000000-lun-0'
            whole_disk: 1
            DTL: 93
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 0 1 2 3
```
