### ISSUE TITLE
IO error on target after incremental receive from unencrypted (old) zvol to encrypted zvol

### ISSUE THREAD

**Issue by koraa** [openzfs/zfs#7634]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| arch linux
Distribution Version	| 
Linux Kernel	| 4.16.13-1-ARCH
Architecture	| x84_64 (i7-7700)
ZFS Version	| 0.7.0-1412_g1a5b96b8e
SPL Version	| 0.7.0-1412_g1a5b96b8e

### Describe the problem you're observing

I performed a `ssh … "zfs send -L -v | …" | … | zfs recv -v` a while ago; the dataset being sent was a zvol in an older pool (`3.19.0-30-generic / i7-2600 / x86_64 / zfs: 0.6.5.4-1~vivid / spl: 0.6.5.4-1~vivid`).
The older pool has compression enabled. The destination on the newer host was as a subvolume of an encrypted volume.

This send worked fine.

Today I started another very small (120mb) incremental send to update the copy on the newer pool.
The send completed successfully, but after the more recent receive, I get `cannot iterate filesystems: I/O error` when doing a `zfs list` and the destination volume no longer shows up.

I can use the old snapshot just fine (by cloning it), but when I try doing anything with the current snapshot (mounting/destroying/cloning) I get IO error.

dmesg and the syslog show no interesting information. No zfs processes/kernel threads in D state.

### ZDB on the source host

Weirdly this bears no correlation to the actual setup on the system…
The actual name of the pool is porpus

```
mind:
    version: 5000
    name: 'mind'
    state: 0 
    txg: 6211540
    pool_guid: 10666323871430758672
    hostname: 'REDACTED'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 10666323871430758672
        children[0]:
            type: 'disk'
            id: 0
            guid: 227987482668599548
            path: '/dev/mapper/mindB'
            whole_disk: 0
            metaslab_array: 33
            metaslab_shift: 34
            ashift: 9
            asize: 2951918125056
            is_log: 0
            create_txg: 4
    features_for_read:
testpool:
    version: 5000
    name: 'testpool'
    state: 0
    txg: 4
    pool_guid: 18090661307219645780
    hostname: 'REDACTED'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 18090661307219645780
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 10581629149302552334
            path: '/dev/mapper/test-zfs'
            whole_disk: 0
            metaslab_array: 33
            metaslab_shift: 29
            ashift: 13
            asize: 67636559872
            is_log: 0
            create_txg: 4
    features_for_read:
```

### ZDB on the destination

```
cadence:                                                                                                                                               
    version: 5000                                                                                                                                      
    name: 'cadence'                                                                                                                                    
    state: 0                                                                                                                                           
    txg: 497                                                                                                                                           
    pool_guid: 3182779468626024901                                                                                                                     
    errata: 0                                                                                                                                          
    hostname: 'REDACTED'                                                                                                                             
    com.delphix:has_per_vdev_zaps                                                                                                                      
    vdev_children: 1                                                                                                                                   
    vdev_tree:                                                                                                                                         
        type: 'root' 
        id: 0
        guid: 3182779468626024901
        create_txg: 4
        children[0]:
            type: 'mirror'
            id: 0
            guid: 4541123782395053351
            whole_disk: 0
            metaslab_array: 256
            metaslab_shift: 34
            ashift: 13
            asize: 1999319334912
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 130
            children[0]:
                type: 'disk'
                id: 0
                guid: 9159395261435864907
                path: '/dev/sdb2'
                whole_disk: 0
                DTL: 392
                create_txg: 4
                com.delphix:vdev_zap_leaf: 129
            children[1]:
                type: 'disk'
                id: 1
                guid: 2753297039320131521
                path: '/dev/sda2'
                whole_disk: 0
                DTL: 263
                create_txg: 4
                com.delphix:vdev_zap_leaf: 132
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data

```
